/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rnentjes/Programming/nimrod/linux-x86_64/f30848148985/lib -o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/core_typeinfo.o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/core_typeinfo.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tnimnode128207 tnimnode128207;
typedef struct tnimtype128211 tnimtype128211;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tany128298 tany128298;
typedef struct TNimType TNimType;
typedef struct tgenseq128304 tgenseq128304;
typedef struct einvalidindex1059 einvalidindex1059;
typedef struct esynch1029 esynch1029;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimNode TNimNode;
typedef struct tcell38448 tcell38448;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tgcheap40616 tgcheap40616;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion22210 tmemregion22210;
typedef struct tsmallchunk21438 tsmallchunk21438;
typedef struct tllchunk22204 tllchunk22204;
typedef struct tbigchunk21440 tbigchunk21440;
typedef struct tintset21415 tintset21415;
typedef struct ttrunk21411 ttrunk21411;
typedef struct tavlnode22208 tavlnode22208;
typedef struct tgcstat40614 tgcstat40614;
typedef struct einvalidvalue1053 einvalidvalue1053;
typedef struct TY131410 TY131410;
typedef struct TY131603 TY131603;
typedef struct tbasechunk21436 tbasechunk21436;
typedef struct tfreecell21428 tfreecell21428;
struct tnimnode128207 {
NU8 Kind;
NI Offset;
tnimtype128211* Typ;
NCSTRING Name;
NI Len;
tnimnode128207** Sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY128288) (void* p, NI op);
struct tnimtype128211 {
NI Size;
NU8 Kind;
NU8 Flags;
tnimtype128211* Base;
tnimnode128207* Node;
void* Finalizer;
TY128288 Marker;
};
struct tany128298 {
void* Value;
tnimtype128211* Rawtype;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct E_Base {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct esynch1029 {
  E_Base Sup;
};
struct einvalidindex1059 {
  esynch1029 Sup;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21438* TY22222[512];
typedef ttrunk21411* ttrunkbuckets21413[256];
struct tintset21415 {
ttrunkbuckets21413 Data;
};
struct tmemregion22210 {
NI Minlargeobj;
NI Maxlargeobj;
TY22222 Freesmallchunks;
tllchunk22204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21440* Freechunkslist;
tintset21415 Chunkstarts;
tavlnode22208* Root;
tavlnode22208* Deleted;
tavlnode22208* Last;
tavlnode22208* Freeavlnodes;
};
struct tgcstat40614 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40616 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
NI64 Maxpause;
tmemregion22210 Region;
tgcstat40614 Stat;
};
struct einvalidvalue1053 {
  esynch1029 Sup;
};
struct tgenseq128304 {
NI Len;
NI Space;
};
struct TY131603 {
NCSTRING Field0;
tany128298 Field1;
};
typedef NI TY21418[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21418 Bits;
};
struct tbasechunk21436 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21438 {
  tbasechunk21436 Sup;
tsmallchunk21438* Next;
tsmallchunk21438* Prev;
tfreecell21428* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk22204 {
NI Size;
NI Acc;
tllchunk22204* Next;
};
struct tbigchunk21440 {
  tbasechunk21436 Sup;
tbigchunk21440* Next;
tbigchunk21440* Prev;
NI Align;
NF Data;
};
struct ttrunk21411 {
ttrunk21411* Next;
NI Key;
TY21418 Bits;
};
typedef tavlnode22208* TY22214[2];
struct tavlnode22208 {
TY22214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21428 {
tfreecell21428* Next;
NI Zerofield;
};
struct TY131410 {
  TGenericSeq Sup;
  TY131603 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, getdiscriminant_128386)(void* aa, tnimnode128207* n);
N_NIMCALL(void, hiddenraiseassert_75217)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(tnimnode128207*, selectbranch_128809)(void* aa, tnimnode128207* n);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(tany128298, newany_128839)(void* value, tnimtype128211* rawtype);
static N_INLINE(NU8, kind_129010)(tany128298 x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, size_129023)(tany128298 x);
static N_INLINE(NU8, basetypekind_129029)(tany128298 x);
static N_INLINE(NI, basetypesize_129054)(tany128298 x);
N_NIMCALL(void, invokenew_129072)(tany128298 x);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, invokenewseq_129205)(tany128298 x, NI len);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, extendseq_129405)(tany128298 x);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, setobjectruntimetype_129608)(tany128298 x);
N_NIMCALL(void, objectInit)(void* dest, TNimType* typ);
static N_INLINE(tnimtype128211*, skiprange_129803)(tnimtype128211* x);
N_NIMCALL(tany128298, HEX5BHEX5D_129817)(tany128298 x, NI i);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38448*, usrtocell_42039)(void* usr);
static N_INLINE(void, rtladdzct_43602)(tcell38448* c);
N_NOINLINE(void, addzct_42015)(tcellseq38464* s, tcell38448* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, HEX5BHEX5DHEX3D_130012)(tany128298 x, NI i, tany128298 y);
N_NIMCALL(NI, len_130612)(tany128298 x);
N_NIMCALL(tany128298, base_130805)(tany128298 x);
N_NIMCALL(NIM_BOOL, isnil_130811)(tany128298 x);
N_NIMCALL(void*, getpointer_131004)(tany128298 x);
N_NIMCALL(void, setpointer_131204)(tany128298 x, void* y);
N_NIMCALL(void, fieldsaux_131404)(void* p, tnimnode128207* n, TY131410** ret);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, cmpignorestyle_132265)(NCSTRING a, NCSTRING b);
static N_INLINE(NIM_CHAR, tolower_132270)(NIM_CHAR c);
N_NIMCALL(tnimnode128207*, getfieldnode_132373)(void* p, tnimnode128207* n, NCSTRING name);
N_NIMCALL(void, HEX5BHEX5DHEX3D_132443)(tany128298 x, NimStringDesc* fieldname, tany128298 value);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(tany128298, HEX5BHEX5D_133022)(tany128298 x, NimStringDesc* fieldname);
N_NIMCALL(tany128298, HEX5BHEX5D_133435)(tany128298 x);
N_NIMCALL(void, HEX5BHEX5DHEX3D_133604)(tany128298 x, tany128298 y);
N_NIMCALL(NI, getint_134004)(tany128298 x);
N_NIMCALL(NI8, getint8_134205)(tany128298 x);
N_NIMCALL(NI16, getint16_134405)(tany128298 x);
N_NIMCALL(NI32, getint32_134605)(tany128298 x);
N_NIMCALL(NI64, getint64_134805)(tany128298 x);
N_NIMCALL(NI64, getbiggestint_135005)(tany128298 x);
N_NIMCALL(void, setbiggestint_135431)(tany128298 x, NI64 y);
N_NIMCALL(NI64, chckRange64)(NI64 i, NI64 a, NI64 b);
N_NIMCALL(NIM_CHAR, getchar_135824)(tany128298 x);
N_NIMCALL(NIM_BOOL, getbool_136005)(tany128298 x);
N_NIMCALL(tany128298, skiprange_136205)(tany128298 x);
N_NIMCALL(NI, getenumordinal_136403)(tany128298 x, NimStringDesc* name);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, getenumfield_136633)(tany128298 x, NI ordinalvalue);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, getenumfield_136839)(tany128298 x);
N_NIMCALL(NF, getfloat_136846)(tany128298 x);
N_NIMCALL(NF32, getfloat32_137005)(tany128298 x);
N_NIMCALL(NF, getfloat64_137205)(tany128298 x);
N_NIMCALL(NF, getbiggestfloat_137405)(tany128298 x);
N_NIMCALL(void, setbiggestfloat_137609)(tany128298 x, NF y);
N_NIMCALL(NimStringDesc*, getstring_137807)(tany128298 x);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, setstring_138007)(tany128298 x, NimStringDesc* y);
N_NIMCALL(NCSTRING, getcstring_138205)(tany128298 x);
N_NIMCALL(void, assign_138405)(tany128298 x, tany128298 y);
N_NIMCALL(void, inclsetelement_138849)(tany128298 x, NI elem);
STRING_LITERAL(TMP157, "n.kind == nkCase ", 17);
STRING_LITERAL(TMP158, "false ", 6);
STRING_LITERAL(TMP159, "x.rawType.kind == tyRef ", 24);
STRING_LITERAL(TMP160, "x.rawType.kind == tySequence ", 29);
STRING_LITERAL(TMP161, "x.rawType.kind == tyObject ", 27);
STRING_LITERAL(TMP163, "index out of bounds", 19);
STRING_LITERAL(TMP166, "sequence is nil", 15);
STRING_LITERAL(TMP171, "y.rawType == x.rawType.base ", 28);
STRING_LITERAL(TMP178, "contains({tyString, tyCString, tyRef, tyPtr, tyPointer, tySeque"
"nce, tyProc}, \012         x.rawType.kind) ", 103);
STRING_LITERAL(TMP181, "not (ret[len(ret) - 1][0] == nil) ", 34);
STRING_LITERAL(TMP187, "contains({tyTuple, tyObject}, x.rawType.kind) ", 46);
STRING_LITERAL(TMP188, "n.typ == value.rawType ", 23);
STRING_LITERAL(TMP190, "invalid field name: ", 20);
STRING_LITERAL(TMP192, "contains({tyRef, tyPtr}, x.rawType.kind) ", 41);
STRING_LITERAL(TMP193, "skipRange(x.rawType).kind == tyInt ", 35);
STRING_LITERAL(TMP194, "skipRange(x.rawType).kind == tyInt8 ", 36);
STRING_LITERAL(TMP195, "skipRange(x.rawType).kind == tyInt16 ", 37);
STRING_LITERAL(TMP196, "skipRange(x.rawType).kind == tyInt32 ", 37);
STRING_LITERAL(TMP197, "skipRange(x.rawType).kind == tyInt64 ", 37);
STRING_LITERAL(TMP198, "t.kind == tyChar ", 17);
STRING_LITERAL(TMP199, "t.kind == tyBool ", 17);
STRING_LITERAL(TMP200, "x.rawType.kind == tyRange ", 26);
STRING_LITERAL(TMP201, "typ.kind == tyEnum ", 19);
STRING_LITERAL(TMP204, "skipRange(x.rawType).kind == tyFloat ", 37);
STRING_LITERAL(TMP205, "skipRange(x.rawType).kind == tyFloat32 ", 39);
STRING_LITERAL(TMP206, "skipRange(x.rawType).kind == tyFloat64 ", 39);
STRING_LITERAL(TMP207, "x.rawType.kind == tyString ", 27);
STRING_LITERAL(TMP208, "x.rawType.kind == tyCString ", 28);
STRING_LITERAL(TMP209, "y.rawType == x.rawType ", 23);
STRING_LITERAL(TMP210, "x.rawType.kind == tySet ", 24);
extern TFrame* frameptr_12025;
extern TNimType NTI15801; /* ref EInvalidIndex */
extern TNimType NTI1059; /* EInvalidIndex */
extern tgcheap40616 gch_40645;
extern TNimType NTI16601; /* ref EInvalidValue */
extern TNimType NTI1053; /* EInvalidValue */

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_12025;
	frameptr_12025 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_12025 = (*frameptr_12025).prev;
}
N_NIMCALL(NI, getdiscriminant_128386)(void* aa, tnimnode128207* n) {
	NI result;
	NI d;
	NI a;
	nimfr("getDiscriminant", "typeinfo.nim")
	result = 0;
	nimln(82, "typeinfo.nim");
	{
		nimln(82, "typeinfo.nim");
		nimln(82, "typeinfo.nim");
		if (!!(((*n).Kind == ((NU8) 3)))) goto LA3;
		nimln(82, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP157));	}	LA3: ;
	d = 0;
	nimln(84, "typeinfo.nim");
	a = ((NI) (aa));
	nimln(85, "typeinfo.nim");
	switch ((*(*n).Typ).Size) {
	case 1:
	{
		nimln(86, "typeinfo.nim");
		nimln(86, "typeinfo.nim");
		nimln(86, "typeinfo.nim");
		d = ((NI)(NU)(NU8)((*((NI8*) ((NI)((NU64)(a) + (NU64)((*n).Offset)))))));
	}	break;
	case 2:
	{
		nimln(87, "typeinfo.nim");
		nimln(87, "typeinfo.nim");
		nimln(87, "typeinfo.nim");
		d = ((NI)(NU)(NU16)((*((NI16*) ((NI)((NU64)(a) + (NU64)((*n).Offset)))))));
	}	break;
	case 4:
	{
		nimln(88, "typeinfo.nim");
		nimln(88, "typeinfo.nim");
		d = ((NI) ((*((NI32*) ((NI)((NU64)(a) + (NU64)((*n).Offset)))))));
	}	break;
	default:
	{
		nimln(89, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA11;
			nimln(89, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA11: ;
	}	break;
	}
	nimln(90, "typeinfo.nim");
	nimln(90, "typeinfo.nim");
	result = d;
	goto BeforeRet;
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(tnimnode128207*, selectbranch_128809)(void* aa, tnimnode128207* n) {
	tnimnode128207* result;
	NI discr;
	nimfr("selectBranch", "typeinfo.nim")
	result = 0;
	nimln(93, "typeinfo.nim");
	discr = getdiscriminant_128386(aa, n);
	nimln(94, "typeinfo.nim");
	{
		nimln(94, "typeinfo.nim");
		if (!((NU64)(discr) < (NU64)((*n).Len))) goto LA3;
		nimln(95, "typeinfo.nim");
		if ((NU)(discr) > (NU)(32767)) raiseIndexError();
		result = (*n).Sons[(discr)- 0];
		nimln(96, "typeinfo.nim");
		{
			nimln(96, "typeinfo.nim");
			if (!(result == NIM_NIL)) goto LA7;
			nimln(96, "typeinfo.nim");
			if ((NU)((*n).Len) > (NU)(32767)) raiseIndexError();
			result = (*n).Sons[((*n).Len)- 0];
		}		LA7: ;
	}	goto LA1;
	LA3: ;
	{
		nimln(99, "typeinfo.nim");
		if ((NU)((*n).Len) > (NU)(32767)) raiseIndexError();
		result = (*n).Sons[((*n).Len)- 0];
	}	LA1: ;
	popFrame();
	return result;
}
N_NIMCALL(tany128298, newany_128839)(void* value, tnimtype128211* rawtype) {
	tany128298 result;
	nimfr("newAny", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(102, "typeinfo.nim");
	result.Value = value;
	nimln(103, "typeinfo.nim");
	result.Rawtype = rawtype;
	popFrame();
	return result;
}
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));	}	LA1: ;
	BeforeRet: ;	return result;
}
static N_INLINE(NU8, kind_129010)(tany128298 x) {
	NU8 result;
	nimfr("kind", "typeinfo.nim")
	result = 0;
	nimln(124, "typeinfo.nim");
	nimln(124, "typeinfo.nim");
	result = ((NU8)chckRange((*x.Rawtype).Kind, ((NU8) 0), ((NU8) 44)));
	popFrame();
	return result;
}
static N_INLINE(NI, size_129023)(tany128298 x) {
	NI result;
	nimfr("size", "typeinfo.nim")
	result = 0;
	nimln(128, "typeinfo.nim");
	result = (*x.Rawtype).Size;
	popFrame();
	return result;
}
static N_INLINE(NU8, basetypekind_129029)(tany128298 x) {
	NU8 result;
	nimfr("baseTypeKind", "typeinfo.nim")
	result = 0;
	nimln(132, "typeinfo.nim");
	{
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!(((*x.Rawtype).Base == NIM_NIL))) goto LA3;
		nimln(133, "typeinfo.nim");
		nimln(133, "typeinfo.nim");
		result = ((NU8)chckRange((*(*x.Rawtype).Base).Kind, ((NU8) 0), ((NU8) 44)));
	}	LA3: ;
	popFrame();
	return result;
}
static N_INLINE(NI, basetypesize_129054)(tany128298 x) {
	NI result;
	nimfr("baseTypeSize", "typeinfo.nim")
	result = 0;
	nimln(137, "typeinfo.nim");
	{
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!(((*x.Rawtype).Base == NIM_NIL))) goto LA3;
		nimln(138, "typeinfo.nim");
		result = (*(*x.Rawtype).Base).Size;
	}	LA3: ;
	popFrame();
	return result;
}
N_NIMCALL(void, invokenew_129072)(tany128298 x) {
	void* z;
	nimfr("invokeNew", "typeinfo.nim")
	nimln(142, "typeinfo.nim");
	{
		nimln(142, "typeinfo.nim");
		nimln(142, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 22)))) goto LA3;
		nimln(142, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP159));	}	LA3: ;
	nimln(143, "typeinfo.nim");
	z = newObj(x.Rawtype, (*(*x.Rawtype).Base).Size);
	nimln(144, "typeinfo.nim");
	genericAssign(x.Value, ((void*) (&z)), x.Rawtype);	popFrame();
}
N_NIMCALL(void, invokenewseq_129205)(tany128298 x, NI len) {
	void* z;
	nimfr("invokeNewSeq", "typeinfo.nim")
	nimln(148, "typeinfo.nim");
	{
		nimln(148, "typeinfo.nim");
		nimln(148, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 24)))) goto LA3;
		nimln(148, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP160));	}	LA3: ;
	nimln(149, "typeinfo.nim");
	z = newSeq(x.Rawtype, len);
	nimln(150, "typeinfo.nim");
	genericShallowAssign(x.Value, ((void*) (&z)), x.Rawtype);	popFrame();
}
N_NIMCALL(void, extendseq_129405)(tany128298 x) {
	tgenseq128304* y;
	tgenseq128304* z;
	nimfr("extendSeq", "typeinfo.nim")
	nimln(154, "typeinfo.nim");
	{
		nimln(154, "typeinfo.nim");
		nimln(154, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 24)))) goto LA3;
		nimln(154, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP160));	}	LA3: ;
	nimln(155, "typeinfo.nim");
	y = (*((tgenseq128304**) (x.Value)));
	nimln(156, "typeinfo.nim");
	z = incrSeq(y, (*(*x.Rawtype).Base).Size);
	nimln(159, "typeinfo.nim");
	(*((void**) (x.Value))) = ((void*) (z));
	popFrame();
}
N_NIMCALL(void, setobjectruntimetype_129608)(tany128298 x) {
	nimfr("setObjectRuntimeType", "typeinfo.nim")
	nimln(164, "typeinfo.nim");
	{
		nimln(164, "typeinfo.nim");
		nimln(164, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 17)))) goto LA3;
		nimln(164, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP161));	}	LA3: ;
	nimln(165, "typeinfo.nim");
	objectInit(x.Value, x.Rawtype);	popFrame();
}
static N_INLINE(tnimtype128211*, skiprange_129803)(tnimtype128211* x) {
	tnimtype128211* result;
	nimfr("skipRange", "typeinfo.nim")
	result = 0;
	nimln(168, "typeinfo.nim");
	result = x;
	nimln(169, "typeinfo.nim");
	{
		nimln(169, "typeinfo.nim");
		if (!((*result).Kind == ((NU8) 20))) goto LA3;
		nimln(169, "typeinfo.nim");
		result = (*result).Base;
	}	LA3: ;
	popFrame();
	return result;
}
static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();	}	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();	}	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;	return result;
}
static N_INLINE(tcell38448*, usrtocell_42039)(void* usr) {
	tcell38448* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	result = ((tcell38448*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38448))))));
	popFrame();
	return result;
}
static N_INLINE(void, rtladdzct_43602)(tcell38448* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(197, "gc.nim");
	addzct_42015(&gch_40645.Zct, c);	popFrame();
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38448* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(231, "gc.nim");
	c = usrtocell_42039(p);
	nimln(233, "gc.nim");
	{
		nimln(165, "gc.nim");
		(*c).Refcount -= 8;
		nimln(166, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(234, "gc.nim");
		rtladdzct_43602(c);	}	LA3: ;
	popFrame();
}
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}	LA5: ;
	raiseOverflow();	BeforeRet: ;	return result;
}
N_NIMCALL(tany128298, HEX5BHEX5D_129817)(tany128298 x, NI i) {
	tany128298 result;
	nimfr("[]", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(173, "typeinfo.nim");
	switch ((*x.Rawtype).Kind) {
	case ((NU8) 16):
	{
		NI bs;
		NI TMP164;
		NI TMP165;
		nimln(175, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(176, "typeinfo.nim");
		{
			NI TMP162;
			einvalidindex1059* e_129833;
			NimStringDesc* LOC6;
			nimln(1198, "system.nim");
			nimln(176, "typeinfo.nim");
			TMP162 = divInt((*x.Rawtype).Size, bs);
			if (!((NU64)((NI64)(TMP162)) <= (NU64)(i))) goto LA4;
			e_129833 = 0;
			nimln(1821, "system.nim");
			e_129833 = (einvalidindex1059*) newObj((&NTI15801), sizeof(einvalidindex1059));
			(*e_129833).Sup.Sup.Sup.m_type = (&NTI1059);
			nimln(1822, "system.nim");
			LOC6 = 0;
			LOC6 = (*e_129833).Sup.Sup.message; (*e_129833).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP163));
			if (LOC6) nimGCunrefNoCycle(LOC6);
			nimln(177, "typeinfo.nim");
			raiseException((E_Base*)e_129833, "EInvalidIndex");
		}		LA4: ;
		nimln(178, "typeinfo.nim");
		nimln(178, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		nimln(178, "typeinfo.nim");
		TMP164 = mulInt(i, bs);
		TMP165 = addInt(((NI) (x.Value)), (NI64)(TMP164));
		result = newany_128839(((void*) ((NI64)(TMP165))), (*x.Rawtype).Base);
		goto BeforeRet;
	}	break;
	case ((NU8) 24):
	{
		void* s;
		NI bs;
		NI TMP167;
		NI TMP168;
		NI TMP169;
		nimln(180, "typeinfo.nim");
		s = (*((void**) (x.Value)));
		nimln(181, "typeinfo.nim");
		{
			einvalidvalue1053* e_129850;
			NimStringDesc* LOC12;
			nimln(181, "typeinfo.nim");
			if (!(s == NIM_NIL)) goto LA10;
			e_129850 = 0;
			nimln(1821, "system.nim");
			e_129850 = (einvalidvalue1053*) newObj((&NTI16601), sizeof(einvalidvalue1053));
			(*e_129850).Sup.Sup.Sup.m_type = (&NTI1053);
			nimln(1822, "system.nim");
			LOC12 = 0;
			LOC12 = (*e_129850).Sup.Sup.message; (*e_129850).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP166));
			if (LOC12) nimGCunrefNoCycle(LOC12);
			nimln(181, "typeinfo.nim");
			raiseException((E_Base*)e_129850, "EInvalidValue");
		}		LA10: ;
		nimln(182, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(183, "typeinfo.nim");
		{
			einvalidindex1059* e_129875;
			NimStringDesc* LOC17;
			nimln(1198, "system.nim");
			if (!((NU64)((*((tgenseq128304*) (s))).Len) <= (NU64)(i))) goto LA15;
			e_129875 = 0;
			nimln(1821, "system.nim");
			e_129875 = (einvalidindex1059*) newObj((&NTI15801), sizeof(einvalidindex1059));
			(*e_129875).Sup.Sup.Sup.m_type = (&NTI1059);
			nimln(1822, "system.nim");
			LOC17 = 0;
			LOC17 = (*e_129875).Sup.Sup.message; (*e_129875).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP163));
			if (LOC17) nimGCunrefNoCycle(LOC17);
			nimln(184, "typeinfo.nim");
			raiseException((E_Base*)e_129875, "EInvalidIndex");
		}		LA15: ;
		nimln(185, "typeinfo.nim");
		nimln(185, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		nimln(185, "typeinfo.nim");
		nimln(185, "typeinfo.nim");
		TMP167 = mulInt(i, bs);
		TMP168 = addInt(16, (NI64)(TMP167));
		TMP169 = addInt(((NI) (s)), (NI64)(TMP168));
		result = newany_128839(((void*) ((NI64)(TMP169))), (*x.Rawtype).Base);
		goto BeforeRet;
	}	break;
	default:
	{
		nimln(186, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA21;
			nimln(186, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA21: ;
	}	break;
	}
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(void, HEX5BHEX5DHEX3D_130012)(tany128298 x, NI i, tany128298 y) {
	nimfr("[]=", "typeinfo.nim")
	nimln(190, "typeinfo.nim");
	switch ((*x.Rawtype).Kind) {
	case ((NU8) 16):
	{
		NI bs;
		NI TMP172;
		NI TMP173;
		nimln(192, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(193, "typeinfo.nim");
		{
			NI TMP170;
			einvalidindex1059* e_130028;
			NimStringDesc* LOC6;
			nimln(1198, "system.nim");
			nimln(193, "typeinfo.nim");
			TMP170 = divInt((*x.Rawtype).Size, bs);
			if (!((NU64)((NI64)(TMP170)) <= (NU64)(i))) goto LA4;
			e_130028 = 0;
			nimln(1821, "system.nim");
			e_130028 = (einvalidindex1059*) newObj((&NTI15801), sizeof(einvalidindex1059));
			(*e_130028).Sup.Sup.Sup.m_type = (&NTI1059);
			nimln(1822, "system.nim");
			LOC6 = 0;
			LOC6 = (*e_130028).Sup.Sup.message; (*e_130028).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP163));
			if (LOC6) nimGCunrefNoCycle(LOC6);
			nimln(194, "typeinfo.nim");
			raiseException((E_Base*)e_130028, "EInvalidIndex");
		}		LA4: ;
		nimln(195, "typeinfo.nim");
		{
			nimln(195, "typeinfo.nim");
			nimln(195, "typeinfo.nim");
			if (!!((y.Rawtype == (*x.Rawtype).Base))) goto LA9;
			nimln(195, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP171));		}		LA9: ;
		nimln(196, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		nimln(196, "typeinfo.nim");
		TMP172 = mulInt(i, bs);
		TMP173 = addInt(((NI) (x.Value)), (NI64)(TMP172));
		genericAssign(((void*) ((NI64)(TMP173))), y.Value, y.Rawtype);	}	break;
	case ((NU8) 24):
	{
		void* s;
		NI bs;
		NI TMP174;
		NI TMP175;
		NI TMP176;
		nimln(198, "typeinfo.nim");
		s = (*((void**) (x.Value)));
		nimln(199, "typeinfo.nim");
		{
			einvalidvalue1053* e_130204;
			NimStringDesc* LOC16;
			nimln(199, "typeinfo.nim");
			if (!(s == NIM_NIL)) goto LA14;
			e_130204 = 0;
			nimln(1821, "system.nim");
			e_130204 = (einvalidvalue1053*) newObj((&NTI16601), sizeof(einvalidvalue1053));
			(*e_130204).Sup.Sup.Sup.m_type = (&NTI1053);
			nimln(1822, "system.nim");
			LOC16 = 0;
			LOC16 = (*e_130204).Sup.Sup.message; (*e_130204).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP166));
			if (LOC16) nimGCunrefNoCycle(LOC16);
			nimln(199, "typeinfo.nim");
			raiseException((E_Base*)e_130204, "EInvalidValue");
		}		LA14: ;
		nimln(200, "typeinfo.nim");
		bs = (*(*x.Rawtype).Base).Size;
		nimln(201, "typeinfo.nim");
		{
			einvalidindex1059* e_130229;
			NimStringDesc* LOC21;
			nimln(1198, "system.nim");
			if (!((NU64)((*((tgenseq128304*) (s))).Len) <= (NU64)(i))) goto LA19;
			e_130229 = 0;
			nimln(1821, "system.nim");
			e_130229 = (einvalidindex1059*) newObj((&NTI15801), sizeof(einvalidindex1059));
			(*e_130229).Sup.Sup.Sup.m_type = (&NTI1059);
			nimln(1822, "system.nim");
			LOC21 = 0;
			LOC21 = (*e_130229).Sup.Sup.message; (*e_130229).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP163));
			if (LOC21) nimGCunrefNoCycle(LOC21);
			nimln(202, "typeinfo.nim");
			raiseException((E_Base*)e_130229, "EInvalidIndex");
		}		LA19: ;
		nimln(203, "typeinfo.nim");
		{
			nimln(203, "typeinfo.nim");
			nimln(203, "typeinfo.nim");
			if (!!((y.Rawtype == (*x.Rawtype).Base))) goto LA24;
			nimln(203, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP171));		}		LA24: ;
		nimln(204, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		nimln(204, "typeinfo.nim");
		nimln(204, "typeinfo.nim");
		TMP174 = mulInt(i, bs);
		TMP175 = addInt(16, (NI64)(TMP174));
		TMP176 = addInt(((NI) (s)), (NI64)(TMP175));
		genericAssign(((void*) ((NI64)(TMP176))), y.Value, y.Rawtype);	}	break;
	default:
	{
		nimln(205, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA29;
			nimln(205, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA29: ;
	}	break;
	}
	popFrame();
}
N_NIMCALL(NI, len_130612)(tany128298 x) {
	NI result;
	nimfr("len", "typeinfo.nim")
	result = 0;
	nimln(209, "typeinfo.nim");
	switch ((*x.Rawtype).Kind) {
	case ((NU8) 16):
	{
		NI TMP177;
		nimln(210, "typeinfo.nim");
		nimln(210, "typeinfo.nim");
		TMP177 = divInt((*x.Rawtype).Size, (*(*x.Rawtype).Base).Size);
		result = (NI64)(TMP177);
	}	break;
	case ((NU8) 24):
	{
		nimln(211, "typeinfo.nim");
		result = (*((tgenseq128304*) ((*((void**) (x.Value)))))).Len;
	}	break;
	default:
	{
		nimln(212, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA6;
			nimln(212, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA6: ;
	}	break;
	}
	popFrame();
	return result;
}
N_NIMCALL(tany128298, base_130805)(tany128298 x) {
	tany128298 result;
	nimfr("base", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(217, "typeinfo.nim");
	result.Rawtype = (*x.Rawtype).Base;
	nimln(218, "typeinfo.nim");
	result.Value = x.Value;
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, isnil_130811)(tany128298 x) {
	NIM_BOOL result;
	nimfr("isNil", "typeinfo.nim")
	result = 0;
	nimln(224, "typeinfo.nim");
	{
		nimln(224, "typeinfo.nim");
		nimln(224, "typeinfo.nim");
		if (!!(((929038336 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(224, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP178));	}	LA3: ;
	nimln(226, "typeinfo.nim");
	nimln(226, "typeinfo.nim");
	result = (*((void**) (x.Value))) == 0;
	popFrame();
	return result;
}
N_NIMCALL(void*, getpointer_131004)(tany128298 x) {
	void* result;
	nimfr("getPointer", "typeinfo.nim")
	result = 0;
	nimln(232, "typeinfo.nim");
	{
		nimln(232, "typeinfo.nim");
		nimln(232, "typeinfo.nim");
		if (!!(((929038336 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(232, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP178));	}	LA3: ;
	nimln(234, "typeinfo.nim");
	result = (*((void**) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(void, setpointer_131204)(tany128298 x, void* y) {
	nimfr("setPointer", "typeinfo.nim")
	nimln(240, "typeinfo.nim");
	{
		nimln(240, "typeinfo.nim");
		nimln(240, "typeinfo.nim");
		if (!!(((929038336 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(240, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP178));	}	LA3: ;
	nimln(242, "typeinfo.nim");
	(*((void**) (x.Value))) = y;
	popFrame();
}
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}	LA5: ;
	raiseOverflow();	BeforeRet: ;	return result;
}
N_NIMCALL(void, fieldsaux_131404)(void* p, tnimnode128207* n, TY131410** ret) {
	nimfr("fieldsAux", "typeinfo.nim")
	nimln(246, "typeinfo.nim");
	switch ((*n).Kind) {
	case ((NU8) 0):
	{
		nimln(247, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA4;
			nimln(247, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA4: ;
	}	break;
	case ((NU8) 1):
	{
		TY131603 LOC7;
		NI TMP179;
		nimln(249, "typeinfo.nim");
		memset((void*)&LOC7, 0, sizeof(LOC7));
		LOC7.Field0 = (*n).Name;
		nimln(249, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		TMP179 = addInt(((NI) (p)), (*n).Offset);
		LOC7.Field1 = newany_128839(((void*) ((NI64)(TMP179))), (*n).Typ);
		(*ret) = (TY131410*) incrSeq(&((*ret))->Sup, sizeof(TY131603));
		(*ret)->data[(*ret)->Sup.len-1] = LOC7;
		nimln(250, "typeinfo.nim");
		{
			NI TMP180;
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			nimln(250, "typeinfo.nim");
			TMP180 = subInt((*ret)->Sup.len, 1);
			if ((NU)((NI64)(TMP180)) >= (NU)((*ret)->Sup.len)) raiseIndexError();
			if (!!(!(((*ret)->data[(NI64)(TMP180)].Field0 == NIM_NIL)))) goto LA10;
			nimln(250, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP181));		}		LA10: ;
	}	break;
	case ((NU8) 2):
	{
		NI i_131810;
		NI HEX3Atmp_131841;
		NI TMP182;
		NI res_131843;
		i_131810 = 0;
		HEX3Atmp_131841 = 0;
		nimln(252, "typeinfo.nim");
		nimln(252, "typeinfo.nim");
		TMP182 = subInt((*n).Len, 1);
		HEX3Atmp_131841 = (NI64)(TMP182);
		nimln(1300, "system.nim");
		res_131843 = 0;
		nimln(1301, "system.nim");
		while (1) {
			nimln(1301, "system.nim");
			if (!(res_131843 <= HEX3Atmp_131841)) goto LA13;
			nimln(1300, "system.nim");
			i_131810 = res_131843;
			nimln(252, "typeinfo.nim");
			if ((NU)(i_131810) > (NU)(32767)) raiseIndexError();
			fieldsaux_131404(p, (*n).Sons[(i_131810)- 0], ret);			nimln(1303, "system.nim");
			res_131843 = addInt(res_131843, 1);
		} LA13: ;
	}	break;
	case ((NU8) 3):
	{
		tnimnode128207* m;
		TY131603 LOC15;
		NI TMP183;
		nimln(254, "typeinfo.nim");
		m = selectbranch_128809(p, n);
		nimln(255, "typeinfo.nim");
		memset((void*)&LOC15, 0, sizeof(LOC15));
		LOC15.Field0 = (*n).Name;
		nimln(255, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		TMP183 = addInt(((NI) (p)), (*n).Offset);
		LOC15.Field1 = newany_128839(((void*) ((NI64)(TMP183))), (*n).Typ);
		(*ret) = (TY131410*) incrSeq(&((*ret))->Sup, sizeof(TY131603));
		(*ret)->data[(*ret)->Sup.len-1] = LOC15;
		nimln(256, "typeinfo.nim");
		{
			nimln(698, "system.nim");
			nimln(698, "system.nim");
			if (!!((m == NIM_NIL))) goto LA18;
			nimln(256, "typeinfo.nim");
			fieldsaux_131404(p, m, ret);		}		LA18: ;
	}	break;
	}
	popFrame();
}
static N_INLINE(NIM_CHAR, tolower_132270)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "typeinfo.nim")
	result = 0;
	nimln(275, "typeinfo.nim");
	{
		NI TMP184;
		nimln(730, "system.nim");
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(275, "typeinfo.nim");
		nimln(275, "typeinfo.nim");
		nimln(275, "typeinfo.nim");
		nimln(275, "typeinfo.nim");
		TMP184 = addInt(((NI) (((NU8)(c)))), 32);
		result = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP184), 0, 255))));
	}	goto LA1;
	LA3: ;
	{
		nimln(276, "typeinfo.nim");
		result = c;
	}	LA1: ;
	popFrame();
	return result;
}
N_NIMCALL(NI, cmpignorestyle_132265)(NCSTRING a, NCSTRING b) {
	NI result;
	NI i;
	NI j;
	nimfr("cmpIgnoreStyle", "typeinfo.nim")
	result = 0;
	nimln(277, "typeinfo.nim");
	i = 0;
	nimln(278, "typeinfo.nim");
	j = 0;
	nimln(279, "typeinfo.nim");
	while (1) {
		NIM_CHAR aa;
		NIM_CHAR bb;
		NI TMP185;
		nimln(280, "typeinfo.nim");
		while (1) {
			nimln(280, "typeinfo.nim");
			if (!((NU8)(a[i]) == (NU8)(95))) goto LA2;
			nimln(280, "typeinfo.nim");
			i = addInt(i, 1);
		} LA2: ;
		nimln(281, "typeinfo.nim");
		while (1) {
			nimln(281, "typeinfo.nim");
			if (!((NU8)(b[j]) == (NU8)(95))) goto LA3;
			nimln(281, "typeinfo.nim");
			j = addInt(j, 1);
		} LA3: ;
		nimln(282, "typeinfo.nim");
		aa = tolower_132270(a[i]);
		nimln(283, "typeinfo.nim");
		bb = tolower_132270(b[j]);
		nimln(284, "typeinfo.nim");
		nimln(284, "typeinfo.nim");
		nimln(284, "typeinfo.nim");
		nimln(284, "typeinfo.nim");
		TMP185 = subInt(((NI) (((NU8)(aa)))), ((NI) (((NU8)(bb)))));
		result = (NI64)(TMP185);
		nimln(285, "typeinfo.nim");
		{
			NIM_BOOL LOC6;
			nimln(285, "typeinfo.nim");
			LOC6 = 0;
			nimln(698, "system.nim");
			nimln(698, "system.nim");
			LOC6 = !((result == 0));
			if (LOC6) goto LA7;
			nimln(285, "typeinfo.nim");
			LOC6 = ((NU8)(aa) == (NU8)(0));
			LA7: ;
			if (!LOC6) goto LA8;
			nimln(285, "typeinfo.nim");
			goto LA1;
		}		LA8: ;
		nimln(286, "typeinfo.nim");
		i = addInt(i, 1);
		nimln(287, "typeinfo.nim");
		j = addInt(j, 1);
	} LA1: ;
	popFrame();
	return result;
}
N_NIMCALL(tnimnode128207*, getfieldnode_132373)(void* p, tnimnode128207* n, NCSTRING name) {
	tnimnode128207* result;
	nimfr("getFieldNode", "typeinfo.nim")
	result = 0;
	nimln(291, "typeinfo.nim");
	switch ((*n).Kind) {
	case ((NU8) 0):
	{
		nimln(292, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA4;
			nimln(292, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA4: ;
	}	break;
	case ((NU8) 1):
	{
		nimln(294, "typeinfo.nim");
		{
			NI LOC9;
			nimln(294, "typeinfo.nim");
			nimln(294, "typeinfo.nim");
			LOC9 = 0;
			LOC9 = cmpignorestyle_132265((*n).Name, name);
			if (!(LOC9 == 0)) goto LA10;
			nimln(295, "typeinfo.nim");
			result = n;
		}		LA10: ;
	}	break;
	case ((NU8) 2):
	{
		NI i_132410;
		NI HEX3Atmp_132436;
		NI TMP186;
		NI res_132438;
		i_132410 = 0;
		HEX3Atmp_132436 = 0;
		nimln(297, "typeinfo.nim");
		nimln(297, "typeinfo.nim");
		TMP186 = subInt((*n).Len, 1);
		HEX3Atmp_132436 = (NI64)(TMP186);
		nimln(1300, "system.nim");
		res_132438 = 0;
		nimln(1301, "system.nim");
		while (1) {
			nimln(1301, "system.nim");
			if (!(res_132438 <= HEX3Atmp_132436)) goto LA13;
			nimln(1300, "system.nim");
			i_132410 = res_132438;
			nimln(298, "typeinfo.nim");
			if ((NU)(i_132410) > (NU)(32767)) raiseIndexError();
			result = getfieldnode_132373(p, (*n).Sons[(i_132410)- 0], name);
			nimln(299, "typeinfo.nim");
			{
				nimln(698, "system.nim");
				nimln(698, "system.nim");
				if (!!((result == NIM_NIL))) goto LA16;
				nimln(299, "typeinfo.nim");
				goto LA13;
			}			LA16: ;
			nimln(1303, "system.nim");
			res_132438 = addInt(res_132438, 1);
		} LA13: ;
	}	break;
	case ((NU8) 3):
	{
		nimln(301, "typeinfo.nim");
		{
			NI LOC21;
			nimln(301, "typeinfo.nim");
			nimln(301, "typeinfo.nim");
			LOC21 = 0;
			LOC21 = cmpignorestyle_132265((*n).Name, name);
			if (!(LOC21 == 0)) goto LA22;
			nimln(302, "typeinfo.nim");
			result = n;
		}		goto LA19;
		LA22: ;
		{
			tnimnode128207* m;
			nimln(304, "typeinfo.nim");
			m = selectbranch_128809(p, n);
			nimln(305, "typeinfo.nim");
			{
				nimln(698, "system.nim");
				nimln(698, "system.nim");
				if (!!((m == NIM_NIL))) goto LA27;
				nimln(305, "typeinfo.nim");
				result = getfieldnode_132373(p, m, name);
			}			LA27: ;
		}		LA19: ;
	}	break;
	}
	popFrame();
	return result;
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));	(*dest).Sup.len += (*src).Sup.len;
}
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(249, "gc.nim");
	{
		tcell38448* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(250, "gc.nim");
		c = usrtocell_42039(src);
		nimln(167, "gc.nim");
		(*c).Refcount += 8;
	}	LA3: ;
	nimln(252, "gc.nim");
	{
		tcell38448* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(253, "gc.nim");
		c = usrtocell_42039((*dest));
		nimln(254, "gc.nim");
		{
			nimln(165, "gc.nim");
			(*c).Refcount -= 8;
			nimln(166, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(255, "gc.nim");
			rtladdzct_43602(c);		}		LA11: ;
	}	LA7: ;
	nimln(256, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(void, HEX5BHEX5DHEX3D_132443)(tany128298 x, NimStringDesc* fieldname, tany128298 value) {
	tnimtype128211* t;
	tnimnode128207* n;
	nimfr("[]=", "typeinfo.nim")
	nimln(309, "typeinfo.nim");
	t = x.Rawtype;
	nimln(313, "typeinfo.nim");
	{
		nimln(313, "typeinfo.nim");
		nimln(313, "typeinfo.nim");
		if (!!(((393216 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(313, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP187));	}	LA3: ;
	nimln(314, "typeinfo.nim");
	n = getfieldnode_132373(x.Value, (*t).Node, fieldname->data);
	nimln(315, "typeinfo.nim");
	{
		NI TMP189;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((n == NIM_NIL))) goto LA7;
		nimln(316, "typeinfo.nim");
		{
			nimln(316, "typeinfo.nim");
			nimln(316, "typeinfo.nim");
			if (!!(((*n).Typ == value.Rawtype))) goto LA11;
			nimln(316, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP188));		}		LA11: ;
		nimln(317, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		TMP189 = addInt(((NI) (x.Value)), (*n).Offset);
		genericAssign(((void*) ((NI64)(TMP189))), value.Value, value.Rawtype);	}	goto LA5;
	LA7: ;
	{
		einvalidvalue1053* e_133003;
		NimStringDesc* LOC14;
		e_133003 = 0;
		nimln(1821, "system.nim");
		e_133003 = (einvalidvalue1053*) newObj((&NTI16601), sizeof(einvalidvalue1053));
		(*e_133003).Sup.Sup.Sup.m_type = (&NTI1053);
		nimln(1822, "system.nim");
		nimln(319, "typeinfo.nim");
		LOC14 = 0;
		LOC14 = rawNewString(fieldname->Sup.len + 20);
appendString(LOC14, ((NimStringDesc*) &TMP190));
appendString(LOC14, fieldname);
		asgnRefNoCycle((void**) &(*e_133003).Sup.Sup.message, LOC14);
		nimln(319, "typeinfo.nim");
		raiseException((E_Base*)e_133003, "EInvalidValue");
	}	LA5: ;
	popFrame();
}
N_NIMCALL(tany128298, HEX5BHEX5D_133022)(tany128298 x, NimStringDesc* fieldname) {
	tany128298 result;
	tnimtype128211* t;
	tnimnode128207* n;
	nimfr("[]", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(323, "typeinfo.nim");
	t = x.Rawtype;
	nimln(327, "typeinfo.nim");
	{
		nimln(327, "typeinfo.nim");
		nimln(327, "typeinfo.nim");
		if (!!(((393216 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(327, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP187));	}	LA3: ;
	nimln(328, "typeinfo.nim");
	n = getfieldnode_132373(x.Value, (*t).Node, fieldname->data);
	nimln(329, "typeinfo.nim");
	{
		NI TMP191;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((n == NIM_NIL))) goto LA7;
		nimln(330, "typeinfo.nim");
		nimln(79, "typeinfo.nim");
		TMP191 = addInt(((NI) (x.Value)), (*n).Offset);
		result.Value = ((void*) ((NI64)(TMP191)));
		nimln(331, "typeinfo.nim");
		result.Rawtype = (*n).Typ;
	}	goto LA5;
	LA7: ;
	{
		einvalidvalue1053* e_133416;
		NimStringDesc* LOC10;
		e_133416 = 0;
		nimln(1821, "system.nim");
		e_133416 = (einvalidvalue1053*) newObj((&NTI16601), sizeof(einvalidvalue1053));
		(*e_133416).Sup.Sup.Sup.m_type = (&NTI1053);
		nimln(1822, "system.nim");
		nimln(333, "typeinfo.nim");
		LOC10 = 0;
		LOC10 = rawNewString(fieldname->Sup.len + 20);
appendString(LOC10, ((NimStringDesc*) &TMP190));
appendString(LOC10, fieldname);
		asgnRefNoCycle((void**) &(*e_133416).Sup.Sup.message, LOC10);
		nimln(333, "typeinfo.nim");
		raiseException((E_Base*)e_133416, "EInvalidValue");
	}	LA5: ;
	popFrame();
	return result;
}
N_NIMCALL(tany128298, HEX5BHEX5D_133435)(tany128298 x) {
	tany128298 result;
	nimfr("[]", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(337, "typeinfo.nim");
	{
		nimln(337, "typeinfo.nim");
		nimln(337, "typeinfo.nim");
		if (!!(((6291456 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(337, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP192));	}	LA3: ;
	nimln(338, "typeinfo.nim");
	result.Value = (*((void**) (x.Value)));
	nimln(339, "typeinfo.nim");
	result.Rawtype = (*x.Rawtype).Base;
	popFrame();
	return result;
}
N_NIMCALL(void, HEX5BHEX5DHEX3D_133604)(tany128298 x, tany128298 y) {
	nimfr("[]=", "typeinfo.nim")
	nimln(343, "typeinfo.nim");
	{
		nimln(343, "typeinfo.nim");
		nimln(343, "typeinfo.nim");
		if (!!(((6291456 &(IL64(1)<<(((*x.Rawtype).Kind)&IL64(63))))!=0))) goto LA3;
		nimln(343, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP192));	}	LA3: ;
	nimln(344, "typeinfo.nim");
	{
		nimln(344, "typeinfo.nim");
		nimln(344, "typeinfo.nim");
		if (!!((y.Rawtype == (*x.Rawtype).Base))) goto LA7;
		nimln(344, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP171));	}	LA7: ;
	nimln(345, "typeinfo.nim");
	genericAssign((*((void**) (x.Value))), y.Value, y.Rawtype);	popFrame();
}
N_NIMCALL(NI, getint_134004)(tany128298 x) {
	NI result;
	nimfr("getInt", "typeinfo.nim")
	result = 0;
	nimln(349, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(349, "typeinfo.nim");
		nimln(349, "typeinfo.nim");
		nimln(349, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 31)))) goto LA4;
		nimln(349, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP193));	}	LA4: ;
	nimln(350, "typeinfo.nim");
	result = (*((NI*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NI8, getint8_134205)(tany128298 x) {
	NI8 result;
	nimfr("getInt8", "typeinfo.nim")
	result = 0;
	nimln(354, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(354, "typeinfo.nim");
		nimln(354, "typeinfo.nim");
		nimln(354, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 32)))) goto LA4;
		nimln(354, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP194));	}	LA4: ;
	nimln(355, "typeinfo.nim");
	result = (*((NI8*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NI16, getint16_134405)(tany128298 x) {
	NI16 result;
	nimfr("getInt16", "typeinfo.nim")
	result = 0;
	nimln(359, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(359, "typeinfo.nim");
		nimln(359, "typeinfo.nim");
		nimln(359, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 33)))) goto LA4;
		nimln(359, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP195));	}	LA4: ;
	nimln(360, "typeinfo.nim");
	result = (*((NI16*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NI32, getint32_134605)(tany128298 x) {
	NI32 result;
	nimfr("getInt32", "typeinfo.nim")
	result = 0;
	nimln(364, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(364, "typeinfo.nim");
		nimln(364, "typeinfo.nim");
		nimln(364, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 34)))) goto LA4;
		nimln(364, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP196));	}	LA4: ;
	nimln(365, "typeinfo.nim");
	result = (*((NI32*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NI64, getint64_134805)(tany128298 x) {
	NI64 result;
	nimfr("getInt64", "typeinfo.nim")
	result = 0;
	nimln(369, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(369, "typeinfo.nim");
		nimln(369, "typeinfo.nim");
		nimln(369, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 35)))) goto LA4;
		nimln(369, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP197));	}	LA4: ;
	nimln(370, "typeinfo.nim");
	result = (*((NI64*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NI64, getbiggestint_135005)(tany128298 x) {
	NI64 result;
	tnimtype128211* t;
	nimfr("getBiggestInt", "typeinfo.nim")
	result = 0;
	nimln(376, "typeinfo.nim");
	t = skiprange_129803(x.Rawtype);
	nimln(377, "typeinfo.nim");
	switch ((*t).Kind) {
	case ((NU8) 31):
	{
		nimln(378, "typeinfo.nim");
		result = ((NI64) ((*((NI*) (x.Value)))));
	}	break;
	case ((NU8) 32):
	{
		nimln(379, "typeinfo.nim");
		result = ((NI64) ((*((NI8*) (x.Value)))));
	}	break;
	case ((NU8) 33):
	{
		nimln(380, "typeinfo.nim");
		result = ((NI64) ((*((NI16*) (x.Value)))));
	}	break;
	case ((NU8) 34):
	{
		nimln(381, "typeinfo.nim");
		result = ((NI64) ((*((NI32*) (x.Value)))));
	}	break;
	case ((NU8) 35):
	case ((NU8) 44):
	{
		nimln(382, "typeinfo.nim");
		result = (*((NI64*) (x.Value)));
	}	break;
	case ((NU8) 1):
	{
		nimln(383, "typeinfo.nim");
		result = ((NI64) ((*((NIM_BOOL*) (x.Value)))));
	}	break;
	case ((NU8) 2):
	{
		nimln(384, "typeinfo.nim");
		result = ((NI64) (((NU8)((*((NIM_CHAR*) (x.Value)))))));
	}	break;
	case ((NU8) 14):
	case ((NU8) 19):
	{
		nimln(386, "typeinfo.nim");
		switch ((*t).Size) {
		case 1:
		{
			nimln(387, "typeinfo.nim");
			nimln(387, "typeinfo.nim");
			result = ((NI64)(NU64)(NU8)((*((NI8*) (x.Value)))));
		}		break;
		case 2:
		{
			nimln(388, "typeinfo.nim");
			nimln(388, "typeinfo.nim");
			result = ((NI64)(NU64)(NU16)((*((NI16*) (x.Value)))));
		}		break;
		case 4:
		{
			nimln(389, "typeinfo.nim");
			result = ((NI64) ((*((NI32*) (x.Value)))));
		}		break;
		case 8:
		{
			nimln(390, "typeinfo.nim");
			result = (*((NI64*) (x.Value)));
		}		break;
		default:
		{
			nimln(391, "typeinfo.nim");
			{
				if (!NIM_TRUE) goto LA16;
				nimln(391, "typeinfo.nim");
				hiddenraiseassert_75217(((NimStringDesc*) &TMP158));			}			LA16: ;
		}		break;
		}
	}	break;
	case ((NU8) 40):
	{
		nimln(392, "typeinfo.nim");
		result = ((NI64) ((*((unsigned long*) (x.Value)))));
	}	break;
	case ((NU8) 41):
	{
		nimln(393, "typeinfo.nim");
		result = ((NI64) ((*((NU8*) (x.Value)))));
	}	break;
	case ((NU8) 42):
	{
		nimln(394, "typeinfo.nim");
		result = ((NI64) ((*((NU16*) (x.Value)))));
	}	break;
	case ((NU8) 43):
	{
		nimln(395, "typeinfo.nim");
		result = ((NI64) ((*((int*) (x.Value)))));
	}	break;
	default:
	{
		nimln(396, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA25;
			nimln(396, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA25: ;
	}	break;
	}
	popFrame();
	return result;
}
N_NIMCALL(void, setbiggestint_135431)(tany128298 x, NI64 y) {
	tnimtype128211* t;
	nimfr("setBiggestInt", "typeinfo.nim")
	nimln(401, "typeinfo.nim");
	t = skiprange_129803(x.Rawtype);
	nimln(402, "typeinfo.nim");
	switch ((*t).Kind) {
	case ((NU8) 31):
	{
		nimln(403, "typeinfo.nim");
		(*((NI*) (x.Value))) = ((NI) (y));
	}	break;
	case ((NU8) 32):
	{
		nimln(404, "typeinfo.nim");
		(*((NI8*) (x.Value))) = ((NI8)chckRange64(y, ((NI8) -128), ((NI8) 127)));
	}	break;
	case ((NU8) 33):
	{
		nimln(405, "typeinfo.nim");
		(*((NI16*) (x.Value))) = ((NI16)chckRange64(y, ((NI16) -32768), ((NI16) 32767)));
	}	break;
	case ((NU8) 34):
	{
		nimln(406, "typeinfo.nim");
		(*((NI32*) (x.Value))) = ((NI32)chckRange64(y, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	}	break;
	case ((NU8) 35):
	case ((NU8) 44):
	{
		nimln(407, "typeinfo.nim");
		(*((NI64*) (x.Value))) = y;
	}	break;
	case ((NU8) 1):
	{
		nimln(408, "typeinfo.nim");
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		(*((NIM_BOOL*) (x.Value))) = !((y == 0));
	}	break;
	case ((NU8) 2):
	{
		nimln(409, "typeinfo.nim");
		nimln(409, "typeinfo.nim");
		(*((NIM_CHAR*) (x.Value))) = ((NIM_CHAR) (((NI)chckRange(((NI) (y)), 0, 255))));
	}	break;
	case ((NU8) 14):
	case ((NU8) 19):
	{
		nimln(411, "typeinfo.nim");
		switch ((*t).Size) {
		case 1:
		{
			nimln(412, "typeinfo.nim");
			nimln(412, "typeinfo.nim");
			(*((NI8*) (x.Value))) = ((NI8)(NU8)(NU)(((NI) (y))));
		}		break;
		case 2:
		{
			nimln(413, "typeinfo.nim");
			nimln(413, "typeinfo.nim");
			(*((NI16*) (x.Value))) = ((NI16)(NU16)(NU)(((NI) (y))));
		}		break;
		case 4:
		{
			nimln(414, "typeinfo.nim");
			(*((NI32*) (x.Value))) = ((NI32)chckRange64(y, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		}		break;
		case 8:
		{
			nimln(415, "typeinfo.nim");
			(*((NI64*) (x.Value))) = y;
		}		break;
		default:
		{
			nimln(416, "typeinfo.nim");
			{
				if (!NIM_TRUE) goto LA16;
				nimln(416, "typeinfo.nim");
				hiddenraiseassert_75217(((NimStringDesc*) &TMP158));			}			LA16: ;
		}		break;
		}
	}	break;
	case ((NU8) 40):
	{
		nimln(417, "typeinfo.nim");
		(*((unsigned long*) (x.Value))) = ((NU) (y));
	}	break;
	case ((NU8) 41):
	{
		nimln(418, "typeinfo.nim");
		(*((NU8*) (x.Value))) = ((NU8) (y));
	}	break;
	case ((NU8) 42):
	{
		nimln(419, "typeinfo.nim");
		(*((NU16*) (x.Value))) = ((NU16) (y));
	}	break;
	case ((NU8) 43):
	{
		nimln(420, "typeinfo.nim");
		(*((int*) (x.Value))) = ((NU32) (y));
	}	break;
	default:
	{
		nimln(421, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA25;
			nimln(421, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA25: ;
	}	break;
	}
	popFrame();
}
N_NIMCALL(NIM_CHAR, getchar_135824)(tany128298 x) {
	NIM_CHAR result;
	tnimtype128211* t;
	nimfr("getChar", "typeinfo.nim")
	result = 0;
	nimln(425, "typeinfo.nim");
	t = skiprange_129803(x.Rawtype);
	nimln(426, "typeinfo.nim");
	{
		nimln(426, "typeinfo.nim");
		nimln(426, "typeinfo.nim");
		if (!!(((*t).Kind == ((NU8) 2)))) goto LA3;
		nimln(426, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP198));	}	LA3: ;
	nimln(427, "typeinfo.nim");
	result = (*((NIM_CHAR*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, getbool_136005)(tany128298 x) {
	NIM_BOOL result;
	tnimtype128211* t;
	nimfr("getBool", "typeinfo.nim")
	result = 0;
	nimln(431, "typeinfo.nim");
	t = skiprange_129803(x.Rawtype);
	nimln(432, "typeinfo.nim");
	{
		nimln(432, "typeinfo.nim");
		nimln(432, "typeinfo.nim");
		if (!!(((*t).Kind == ((NU8) 1)))) goto LA3;
		nimln(432, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP199));	}	LA3: ;
	nimln(433, "typeinfo.nim");
	result = (*((NIM_BOOL*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(tany128298, skiprange_136205)(tany128298 x) {
	tany128298 result;
	nimfr("skipRange", "typeinfo.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(437, "typeinfo.nim");
	{
		nimln(437, "typeinfo.nim");
		nimln(437, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 20)))) goto LA3;
		nimln(437, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP200));	}	LA3: ;
	nimln(438, "typeinfo.nim");
	result.Rawtype = (*x.Rawtype).Base;
	nimln(439, "typeinfo.nim");
	result.Value = x.Value;
	popFrame();
	return result;
}
N_NIMCALL(NI, getenumordinal_136403)(tany128298 x, NimStringDesc* name) {
	NI result;
	tnimtype128211* typ;
	tnimnode128207* n;
	tnimnode128207** s;
	NI i_136612;
	NI HEX3Atmp_136624;
	NI TMP202;
	NI res_136626;
	nimfr("getEnumOrdinal", "typeinfo.nim")
	result = 0;
	nimln(445, "typeinfo.nim");
	typ = skiprange_129803(x.Rawtype);
	nimln(446, "typeinfo.nim");
	{
		nimln(446, "typeinfo.nim");
		nimln(446, "typeinfo.nim");
		if (!!(((*typ).Kind == ((NU8) 14)))) goto LA3;
		nimln(446, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP201));	}	LA3: ;
	nimln(447, "typeinfo.nim");
	n = (*typ).Node;
	nimln(448, "typeinfo.nim");
	s = (*n).Sons;
	i_136612 = 0;
	HEX3Atmp_136624 = 0;
	nimln(449, "typeinfo.nim");
	nimln(449, "typeinfo.nim");
	TMP202 = subInt((*n).Len, 1);
	HEX3Atmp_136624 = (NI64)(TMP202);
	nimln(1300, "system.nim");
	res_136626 = 0;
	nimln(1301, "system.nim");
	while (1) {
		nimln(1301, "system.nim");
		if (!(res_136626 <= HEX3Atmp_136624)) goto LA5;
		nimln(1300, "system.nim");
		i_136612 = res_136626;
		nimln(450, "typeinfo.nim");
		{
			NimStringDesc* LOC8;
			NI LOC9;
			nimln(450, "typeinfo.nim");
			nimln(450, "typeinfo.nim");
			nimln(450, "typeinfo.nim");
			if ((NU)(i_136612) > (NU)(32767)) raiseIndexError();
			LOC8 = 0;
			LOC8 = cstrToNimstr((*s[(i_136612)- 0]).Name);
			LOC9 = 0;
			LOC9 = cmpignorestyle_132265(LOC8->data, name->data);
			if (!(LOC9 == 0)) goto LA10;
			nimln(451, "typeinfo.nim");
			{
				nimln(731, "system.nim");
				nimln(731, "system.nim");
				if (!!((((*typ).Flags &(1<<((((NU8) 2))&7)))!=0))) goto LA14;
				nimln(452, "typeinfo.nim");
				nimln(452, "typeinfo.nim");
				result = i_136612;
				goto BeforeRet;
			}			goto LA12;
			LA14: ;
			{
				nimln(454, "typeinfo.nim");
				nimln(454, "typeinfo.nim");
				if ((NU)(i_136612) > (NU)(32767)) raiseIndexError();
				result = (*s[(i_136612)- 0]).Offset;
				goto BeforeRet;
			}			LA12: ;
		}		LA10: ;
		nimln(1303, "system.nim");
		res_136626 = addInt(res_136626, 1);
	} LA5: ;
	nimln(455, "typeinfo.nim");
	result = (IL64(-9223372036854775807) - IL64(1));
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(NimStringDesc*, getenumfield_136633)(tany128298 x, NI ordinalvalue) {
	NimStringDesc* result;
	tnimtype128211* typ;
	NI e;
	nimfr("getEnumField", "typeinfo.nim")
	result = 0;
	nimln(461, "typeinfo.nim");
	typ = skiprange_129803(x.Rawtype);
	nimln(462, "typeinfo.nim");
	{
		nimln(462, "typeinfo.nim");
		nimln(462, "typeinfo.nim");
		if (!!(((*typ).Kind == ((NU8) 14)))) goto LA3;
		nimln(462, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP201));	}	LA3: ;
	nimln(463, "typeinfo.nim");
	e = ordinalvalue;
	nimln(464, "typeinfo.nim");
	{
		nimln(731, "system.nim");
		nimln(731, "system.nim");
		if (!!((((*typ).Flags &(1<<((((NU8) 2))&7)))!=0))) goto LA7;
		nimln(465, "typeinfo.nim");
		{
			nimln(465, "typeinfo.nim");
			if (!((NU64)(e) < (NU64)((*(*typ).Node).Len))) goto LA11;
			nimln(466, "typeinfo.nim");
			nimln(466, "typeinfo.nim");
			nimln(466, "typeinfo.nim");
			if ((NU)(e) > (NU)(32767)) raiseIndexError();
			result = cstrToNimstr((*(*(*typ).Node).Sons[(e)- 0]).Name);
			goto BeforeRet;
		}		LA11: ;
	}	goto LA5;
	LA7: ;
	{
		tnimnode128207* n;
		tnimnode128207** s;
		NI i_136831;
		NI HEX3Atmp_136832;
		NI TMP203;
		NI res_136834;
		nimln(469, "typeinfo.nim");
		n = (*typ).Node;
		nimln(470, "typeinfo.nim");
		s = (*n).Sons;
		i_136831 = 0;
		HEX3Atmp_136832 = 0;
		nimln(471, "typeinfo.nim");
		nimln(471, "typeinfo.nim");
		TMP203 = subInt((*n).Len, 1);
		HEX3Atmp_136832 = (NI64)(TMP203);
		nimln(1300, "system.nim");
		res_136834 = 0;
		nimln(1301, "system.nim");
		while (1) {
			nimln(1301, "system.nim");
			if (!(res_136834 <= HEX3Atmp_136832)) goto LA14;
			nimln(1300, "system.nim");
			i_136831 = res_136834;
			nimln(472, "typeinfo.nim");
			{
				nimln(472, "typeinfo.nim");
				if ((NU)(i_136831) > (NU)(32767)) raiseIndexError();
				if (!((*s[(i_136831)- 0]).Offset == e)) goto LA17;
				nimln(472, "typeinfo.nim");
				nimln(472, "typeinfo.nim");
				nimln(472, "typeinfo.nim");
				if ((NU)(i_136831) > (NU)(32767)) raiseIndexError();
				result = cstrToNimstr((*s[(i_136831)- 0]).Name);
				goto BeforeRet;
			}			LA17: ;
			nimln(1303, "system.nim");
			res_136834 = addInt(res_136834, 1);
		} LA14: ;
	}	LA5: ;
	nimln(473, "typeinfo.nim");
	nimln(473, "typeinfo.nim");
	result = nimIntToStr(e);
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(NimStringDesc*, getenumfield_136839)(tany128298 x) {
	NimStringDesc* result;
	NI64 LOC1;
	nimfr("getEnumField", "typeinfo.nim")
	result = 0;
	nimln(477, "typeinfo.nim");
	nimln(477, "typeinfo.nim");
	LOC1 = 0;
	LOC1 = getbiggestint_135005(x);
	result = getenumfield_136633(x, ((NI) (LOC1)));
	popFrame();
	return result;
}
N_NIMCALL(NF, getfloat_136846)(tany128298 x) {
	NF result;
	nimfr("getFloat", "typeinfo.nim")
	result = 0;
	nimln(481, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(481, "typeinfo.nim");
		nimln(481, "typeinfo.nim");
		nimln(481, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 36)))) goto LA4;
		nimln(481, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP204));	}	LA4: ;
	nimln(482, "typeinfo.nim");
	result = (*((NF*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NF32, getfloat32_137005)(tany128298 x) {
	NF32 result;
	nimfr("getFloat32", "typeinfo.nim")
	result = 0;
	nimln(486, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(486, "typeinfo.nim");
		nimln(486, "typeinfo.nim");
		nimln(486, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 37)))) goto LA4;
		nimln(486, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP205));	}	LA4: ;
	nimln(487, "typeinfo.nim");
	result = (*((NF32*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NF, getfloat64_137205)(tany128298 x) {
	NF result;
	nimfr("getFloat64", "typeinfo.nim")
	result = 0;
	nimln(491, "typeinfo.nim");
	{
		tnimtype128211* LOC3;
		nimln(491, "typeinfo.nim");
		nimln(491, "typeinfo.nim");
		nimln(491, "typeinfo.nim");
		LOC3 = 0;
		LOC3 = skiprange_129803(x.Rawtype);
		if (!!(((*LOC3).Kind == ((NU8) 38)))) goto LA4;
		nimln(491, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP206));	}	LA4: ;
	nimln(492, "typeinfo.nim");
	result = (*((NF*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(NF, getbiggestfloat_137405)(tany128298 x) {
	NF result;
	tnimtype128211* LOC1;
	nimfr("getBiggestFloat", "typeinfo.nim")
	result = 0;
	nimln(497, "typeinfo.nim");
	nimln(497, "typeinfo.nim");
	LOC1 = 0;
	LOC1 = skiprange_129803(x.Rawtype);
	switch ((*LOC1).Kind) {
	case ((NU8) 36):
	{
		nimln(498, "typeinfo.nim");
		result = (*((NF*) (x.Value)));
	}	break;
	case ((NU8) 37):
	{
		nimln(499, "typeinfo.nim");
		result = ((NF) ((*((NF32*) (x.Value)))));
	}	break;
	case ((NU8) 38):
	{
		nimln(500, "typeinfo.nim");
		result = (*((NF*) (x.Value)));
	}	break;
	default:
	{
		nimln(501, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA8;
			nimln(501, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA8: ;
	}	break;
	}
	popFrame();
	return result;
}
N_NIMCALL(void, setbiggestfloat_137609)(tany128298 x, NF y) {
	tnimtype128211* LOC1;
	nimfr("setBiggestFloat", "typeinfo.nim")
	nimln(506, "typeinfo.nim");
	nimln(506, "typeinfo.nim");
	LOC1 = 0;
	LOC1 = skiprange_129803(x.Rawtype);
	switch ((*LOC1).Kind) {
	case ((NU8) 36):
	{
		nimln(507, "typeinfo.nim");
		(*((NF*) (x.Value))) = y;
	}	break;
	case ((NU8) 37):
	{
		nimln(508, "typeinfo.nim");
		(*((NF32*) (x.Value))) = ((NF32) (y));
	}	break;
	case ((NU8) 38):
	{
		nimln(509, "typeinfo.nim");
		(*((NF*) (x.Value))) = y;
	}	break;
	default:
	{
		nimln(510, "typeinfo.nim");
		{
			if (!NIM_TRUE) goto LA8;
			nimln(510, "typeinfo.nim");
			hiddenraiseassert_75217(((NimStringDesc*) &TMP158));		}		LA8: ;
	}	break;
	}
	popFrame();
}
N_NIMCALL(NimStringDesc*, getstring_137807)(tany128298 x) {
	NimStringDesc* result;
	nimfr("getString", "typeinfo.nim")
	result = 0;
	nimln(514, "typeinfo.nim");
	{
		nimln(514, "typeinfo.nim");
		nimln(514, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 28)))) goto LA3;
		nimln(514, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP207));	}	LA3: ;
	nimln(515, "typeinfo.nim");
	{
		nimln(515, "typeinfo.nim");
		nimln(515, "typeinfo.nim");
		if (!!((*((void**) (x.Value))) == 0)) goto LA7;
		nimln(516, "typeinfo.nim");
		unsureAsgnRef((void**) &result, copyString((*((NimStringDesc**) (x.Value)))));
	}	LA7: ;
	popFrame();
	return result;
}
N_NIMCALL(void, setstring_138007)(tany128298 x, NimStringDesc* y) {
	nimfr("setString", "typeinfo.nim")
	nimln(520, "typeinfo.nim");
	{
		nimln(520, "typeinfo.nim");
		nimln(520, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 28)))) goto LA3;
		nimln(520, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP207));	}	LA3: ;
	nimln(521, "typeinfo.nim");
	unsureAsgnRef((void**) &(*((NimStringDesc**) (x.Value))), copyString(y));
	popFrame();
}
N_NIMCALL(NCSTRING, getcstring_138205)(tany128298 x) {
	NCSTRING result;
	nimfr("getCString", "typeinfo.nim")
	result = 0;
	nimln(525, "typeinfo.nim");
	{
		nimln(525, "typeinfo.nim");
		nimln(525, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 29)))) goto LA3;
		nimln(525, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP208));	}	LA3: ;
	nimln(526, "typeinfo.nim");
	result = (*((NCSTRING*) (x.Value)));
	popFrame();
	return result;
}
N_NIMCALL(void, assign_138405)(tany128298 x, tany128298 y) {
	nimfr("assign", "typeinfo.nim")
	nimln(531, "typeinfo.nim");
	{
		nimln(531, "typeinfo.nim");
		nimln(531, "typeinfo.nim");
		if (!!((y.Rawtype == x.Rawtype))) goto LA3;
		nimln(531, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP209));	}	LA3: ;
	nimln(532, "typeinfo.nim");
	genericAssign(x.Value, y.Value, y.Rawtype);	popFrame();
}
N_NIMCALL(void, inclsetelement_138849)(tany128298 x, NI elem) {
	tnimtype128211* typ;
	void* p;
	NI e;
	NI TMP211;
	nimfr("inclSetElement", "typeinfo.nim")
	nimln(558, "typeinfo.nim");
	{
		nimln(558, "typeinfo.nim");
		nimln(558, "typeinfo.nim");
		if (!!(((*x.Rawtype).Kind == ((NU8) 19)))) goto LA3;
		nimln(558, "typeinfo.nim");
		hiddenraiseassert_75217(((NimStringDesc*) &TMP210));	}	LA3: ;
	nimln(559, "typeinfo.nim");
	typ = x.Rawtype;
	nimln(560, "typeinfo.nim");
	p = x.Value;
	nimln(562, "typeinfo.nim");
	nimln(562, "typeinfo.nim");
	TMP211 = subInt(elem, (*(*typ).Node).Len);
	e = (NI64)(TMP211);
	nimln(563, "typeinfo.nim");
	switch ((*typ).Size) {
	case 1:
	{
		NI8* a;
		nimln(565, "typeinfo.nim");
		a = ((NI8*) (p));
		nimln(566, "typeinfo.nim");
		nimln(566, "typeinfo.nim");
		nimln(566, "typeinfo.nim");
		(*a) = (NI8)((*a) | (NI8)((NU8)(((NI8) 1)) << (NU8)(((NI8)chckRange(e, ((NI8) -128), ((NI8) 127))))));
	}	break;
	case 2:
	{
		NI16* a;
		nimln(568, "typeinfo.nim");
		a = ((NI16*) (p));
		nimln(569, "typeinfo.nim");
		nimln(569, "typeinfo.nim");
		nimln(569, "typeinfo.nim");
		(*a) = (NI16)((*a) | (NI16)((NU16)(((NI16) 1)) << (NU16)(((NI16)chckRange(e, ((NI16) -32768), ((NI16) 32767))))));
	}	break;
	case 4:
	{
		NI32* a;
		nimln(571, "typeinfo.nim");
		a = ((NI32*) (p));
		nimln(572, "typeinfo.nim");
		nimln(572, "typeinfo.nim");
		nimln(572, "typeinfo.nim");
		(*a) = (NI32)((*a) | (NI32)((NU32)(((NI32) 1)) << (NU32)(((NI32)chckRange(e, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))))));
	}	break;
	case 8:
	{
		NI64* a;
		nimln(574, "typeinfo.nim");
		a = ((NI64*) (p));
		nimln(575, "typeinfo.nim");
		nimln(575, "typeinfo.nim");
		nimln(575, "typeinfo.nim");
		(*a) = (NI64)((*a) | (NI64)((NU64)(1) << (NU64)(((NI64) (e)))));
	}	break;
	default:
	{
		NI8* a;
		nimln(577, "typeinfo.nim");
		a = ((NI8*) (p));
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		if ((NU)((NI)((NU64)(e) >> (NU64)(3))) > (NU)(65535)) raiseIndexError();
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		if ((NU)((NI)((NU64)(e) >> (NU64)(3))) > (NU)(65535)) raiseIndexError();
		nimln(578, "typeinfo.nim");
		nimln(578, "typeinfo.nim");
		a[((NI)((NU64)(e) >> (NU64)(3)))- 0] = ((NI8)(NU8)(NU)((NI)(((NI) (a[((NI)((NU64)(e) >> (NU64)(3)))- 0])) | (NI)((NU64)(1) << (NU64)(((NI) ((NI)(e & 7))))))));
	}	break;
	}
	popFrame();
}N_NOINLINE(void, coretypeinfoInit)(void) {
	nimfr("typeinfo", "typeinfo.nim")
	popFrame();
}

N_NOINLINE(void, coretypeinfoDatInit)(void) {
}

