/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rnentjes/Programming/nimrod/linux-x86_64/f30848148985/lib -o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/opengl_opengl.o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/opengl_opengl.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_CDECL_PTR(void*, TY94201) (NCSTRING s);
typedef N_CDECL_PTR(void*, TY94205) (NCSTRING s);
typedef N_STDCALL_PTR(void, TY104296) (NI32 x, NI32 y, NI32 width, NI32 height);
typedef N_STDCALL_PTR(NI, TY106846) (NU32 shadertype);
typedef N_STDCALL_PTR(void, TY106993) (NI shaderobj, NI32 count, NCSTRING* string, NI32* lengths);
typedef N_STDCALL_PTR(void, TY106839) (NI shaderobj);
typedef N_STDCALL_PTR(void, TY106924) (NI shaderobj, NU32 pname, NI32* params);
typedef N_STDCALL_PTR(void, TY106930) (NI shaderobj, NI32 maxlength, NI32* len, NCSTRING infolog);
typedef N_STDCALL_PTR(void, TY104133) (NF32 red, NF32 green, NF32 blue, NF32 alpha);
typedef N_STDCALL_PTR(NI, TY106843) (void);
typedef N_STDCALL_PTR(void, TY106828) (NI programobj, NI shaderobj);
typedef N_STDCALL_PTR(void, TY106989) (NI programobj);
typedef N_STDCALL_PTR(void, TY106910) (NI programobj, NU32 pname, NI32* params);
typedef N_STDCALL_PTR(void, TY107000) (NI programobj);
typedef N_STDCALL_PTR(NI32, TY106905) (NI programobj, NCSTRING char_106907);
typedef N_STDCALL_PTR(void, TY106867) (NU32 index);
typedef N_STDCALL_PTR(void, TY106748) (NI32 n, int* buffers);
typedef N_STDCALL_PTR(void, TY106738) (NU32 target, NU32 buffer);
typedef N_STDCALL_PTR(void, TY106757) (NU32 target, NI32 size, void* data, NU32 usage);
typedef N_STDCALL_PTR(void, TY104129) (NU32 mask);
typedef N_STDCALL_PTR(void, TY107330) (NU32 index, NI32 size, NU32 typ, NIM_BOOL normalized, NI32 stride, void* pointer);
typedef N_STDCALL_PTR(void, TY104303) (NU32 mode, NI32 first, NI32 count);
N_NIMCALL(void*, loadlib_93408)(NimStringDesc* path);
N_NIMCALL(void, quit_74629)(NimStringDesc* errormsg, NI errorcode);
N_NIMCALL(void*, symaddr_93439)(void* lib, NCSTRING name);
N_NIMCALL(void*, glgetproc_94209)(void* h, NCSTRING procname);
N_NOINLINE(void, raiseinvalidlibrary_93419)(NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, glugetproc_94415)(NCSTRING procname);
STRING_LITERAL(TMP147, "libGL.so.1", 10);
STRING_LITERAL(TMP148, "could not load: libGL.so.1", 26);
STRING_LITERAL(TMP149, "libGLU.so.1", 11);
STRING_LITERAL(TMP150, "could not load: libGLU.so.1", 27);
void* oglhandle_94001;
TY94201 glxgetprocaddress_94204;
TY94205 glxgetprocaddressarb_94208;
extern TFrame* frameptr_12025;
void* gluhandle_94414;
NI lastpixelformat_119131;
TY104296 Dl_104295;
TY106846 Dl_106845;
TY106993 Dl_106992;
TY106839 Dl_106838;
TY106924 Dl_106923;
TY106930 Dl_106929;
TY104133 Dl_104132;
TY106843 Dl_106842;
TY106828 Dl_106827;
TY106989 Dl_106988;
TY106910 Dl_106909;
TY107000 Dl_106999;
TY106905 Dl_106904;
TY106867 Dl_106866;
TY106748 Dl_106747;
TY106738 Dl_106737;
TY106757 Dl_106756;
TY104129 Dl_104128;
TY107330 Dl_107329;
TY104303 Dl_104302;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_12025;
	frameptr_12025 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_12025 = (*frameptr_12025).prev;
}
N_NIMCALL(void*, glgetproc_94209)(void* h, NCSTRING procname) {
	void* result;
	nimfr("glGetProc", "opengl.nim")
	result = 0;
	nimln(63, "opengl.nim");
	{
		nimln(63, "opengl.nim");
		nimln(63, "opengl.nim");
		if (!!(glxgetprocaddress_94204 == 0)) goto LA3;
		nimln(63, "opengl.nim");
		result = glxgetprocaddress_94204(procname);
	}	LA3: ;
	nimln(64, "opengl.nim");
	{
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((result == NIM_NIL))) goto LA7;
		nimln(64, "opengl.nim");
		goto BeforeRet;
	}	LA7: ;
	nimln(65, "opengl.nim");
	{
		nimln(65, "opengl.nim");
		nimln(65, "opengl.nim");
		if (!!(glxgetprocaddressarb_94208 == 0)) goto LA11;
		nimln(66, "opengl.nim");
		result = glxgetprocaddressarb_94208(procname);
		nimln(67, "opengl.nim");
		{
			nimln(698, "system.nim");
			nimln(698, "system.nim");
			if (!!((result == NIM_NIL))) goto LA15;
			nimln(67, "opengl.nim");
			goto BeforeRet;
		}		LA15: ;
	}	LA11: ;
	nimln(68, "opengl.nim");
	result = symaddr_93439(h, procname);
	nimln(71, "opengl.nim");
	{
		nimln(71, "opengl.nim");
		if (!(result == NIM_NIL)) goto LA19;
		nimln(71, "opengl.nim");
		raiseinvalidlibrary_93419(procname);	}	LA19: ;
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(void*, glugetproc_94415)(NCSTRING procname) {
	void* result;
	nimfr("gluGetProc", "opengl.nim")
	result = 0;
	nimln(76, "opengl.nim");
	{
		nimln(76, "opengl.nim");
		if (!(gluhandle_94414 == NIM_NIL)) goto LA3;
		nimln(77, "opengl.nim");
		gluhandle_94414 = loadlib_93408(((NimStringDesc*) &TMP149));
		nimln(78, "opengl.nim");
		{
			nimln(78, "opengl.nim");
			if (!(gluhandle_94414 == NIM_NIL)) goto LA7;
			nimln(78, "opengl.nim");
			quit_74629(((NimStringDesc*) &TMP150), 1);		}		LA7: ;
	}	LA3: ;
	nimln(79, "opengl.nim");
	result = glgetproc_94209(gluhandle_94414, procname);
	popFrame();
	return result;
}N_NOINLINE(void, openglopenglInit)(void) {
	void* LOC5;
	void* LOC6;
	nimfr("opengl", "opengl.nim")
	nimln(45, "opengl.nim");
	oglhandle_94001 = loadlib_93408(((NimStringDesc*) &TMP147));
	nimln(46, "opengl.nim");
	{
		nimln(46, "opengl.nim");
		if (!oglhandle_94001 == 0) goto LA3;
		nimln(46, "opengl.nim");
		quit_74629(((NimStringDesc*) &TMP148), 1);	}	LA3: ;
	nimln(52, "opengl.nim");
	nimln(53, "opengl.nim");
	LOC5 = 0;
	LOC5 = symaddr_93439(oglhandle_94001, "glXGetProcAddress");
	glxgetprocaddress_94204 = ((TY94201) (LOC5));
	nimln(54, "opengl.nim");
	nimln(55, "opengl.nim");
	LOC6 = 0;
	LOC6 = symaddr_93439(oglhandle_94001, "glXGetProcAddressARB");
	glxgetprocaddressarb_94208 = ((TY94205) (LOC6));
	popFrame();
}

N_NOINLINE(void, openglopenglDatInit)(void) {
}

N_NIMCALL(void, nimLoadProcs0)(void) {	Dl_104295 = (TY104296) (glgetproc_94209(oglhandle_94001, "glViewport"));
	Dl_106845 = (TY106846) (glgetproc_94209(oglhandle_94001, "glCreateShader"));
	Dl_106992 = (TY106993) (glgetproc_94209(oglhandle_94001, "glShaderSource"));
	Dl_106838 = (TY106839) (glgetproc_94209(oglhandle_94001, "glCompileShader"));
	Dl_106923 = (TY106924) (glgetproc_94209(oglhandle_94001, "glGetShaderiv"));
	Dl_106929 = (TY106930) (glgetproc_94209(oglhandle_94001, "glGetShaderInfoLog"));
	Dl_104132 = (TY104133) (glgetproc_94209(oglhandle_94001, "glClearColor"));
	Dl_106842 = (TY106843) (glgetproc_94209(oglhandle_94001, "glCreateProgram"));
	Dl_106827 = (TY106828) (glgetproc_94209(oglhandle_94001, "glAttachShader"));
	Dl_106988 = (TY106989) (glgetproc_94209(oglhandle_94001, "glLinkProgram"));
	Dl_106909 = (TY106910) (glgetproc_94209(oglhandle_94001, "glGetProgramiv"));
	Dl_106999 = (TY107000) (glgetproc_94209(oglhandle_94001, "glUseProgram"));
	Dl_106904 = (TY106905) (glgetproc_94209(oglhandle_94001, "glGetAttribLocation"));
	Dl_106866 = (TY106867) (glgetproc_94209(oglhandle_94001, "glEnableVertexAttribArray"));
	Dl_106747 = (TY106748) (glgetproc_94209(oglhandle_94001, "glGenBuffers"));
	Dl_106737 = (TY106738) (glgetproc_94209(oglhandle_94001, "glBindBuffer"));
	Dl_106756 = (TY106757) (glgetproc_94209(oglhandle_94001, "glBufferData"));
	Dl_104128 = (TY104129) (glgetproc_94209(oglhandle_94001, "glClear"));
	Dl_107329 = (TY107330) (glgetproc_94209(oglhandle_94001, "glVertexAttribPointer"));
	Dl_104302 = (TY104303) (glgetproc_94209(oglhandle_94001, "glDrawArrays"));
}

