/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rnentjes/Programming/nimrod/linux-x86_64/f30848148985/lib -o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/pure_strutils.o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/pure_strutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct einvalidvalue1053 einvalidvalue1053;
typedef struct esynch1029 esynch1029;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38448 tcell38448;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tgcheap40616 tgcheap40616;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion22210 tmemregion22210;
typedef struct tsmallchunk21438 tsmallchunk21438;
typedef struct tllchunk22204 tllchunk22204;
typedef struct tbigchunk21440 tbigchunk21440;
typedef struct tintset21415 tintset21415;
typedef struct ttrunk21411 ttrunk21411;
typedef struct tavlnode22208 tavlnode22208;
typedef struct tgcstat40614 tgcstat40614;
typedef struct tbasechunk21436 tbasechunk21436;
typedef struct tfreecell21428 tfreecell21428;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct E_Base {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct esynch1029 {
  E_Base Sup;
};
struct einvalidvalue1053 {
  esynch1029 Sup;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21438* TY22222[512];
typedef ttrunk21411* ttrunkbuckets21413[256];
struct tintset21415 {
ttrunkbuckets21413 Data;
};
struct tmemregion22210 {
NI Minlargeobj;
NI Maxlargeobj;
TY22222 Freesmallchunks;
tllchunk22204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21440* Freechunkslist;
tintset21415 Chunkstarts;
tavlnode22208* Root;
tavlnode22208* Deleted;
tavlnode22208* Last;
tavlnode22208* Freeavlnodes;
};
struct tgcstat40614 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40616 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
NI64 Maxpause;
tmemregion22210 Region;
tgcstat40614 Stat;
};
typedef NimStringDesc* TY142070[1];
typedef NI TY21418[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21418 Bits;
};
struct tbasechunk21436 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21438 {
  tbasechunk21436 Sup;
tsmallchunk21438* Next;
tsmallchunk21438* Prev;
tfreecell21428* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk22204 {
NI Size;
NI Acc;
tllchunk22204* Next;
};
struct tbigchunk21440 {
  tbasechunk21436 Sup;
tbigchunk21440* Next;
tbigchunk21440* Prev;
NI Align;
NF Data;
};
struct ttrunk21411 {
ttrunk21411* Next;
NI Key;
TY21418 Bits;
};
typedef tavlnode22208* TY22214[2];
struct tavlnode22208 {
TY22214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21428 {
tfreecell21428* Next;
NI Zerofield;
};
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, raiseIndexError)(void);
N_NOINLINE(void, invalidformatstring_126823)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38448*, usrtocell_42039)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_43602)(tcell38448* c);
N_NOINLINE(void, addzct_42015)(tcellseq38464* s, tcell38448* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, findnormalized_126802)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_67023, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
STRING_LITERAL(TMP228, "invalid format string", 21);
extern TNimType NTI16601; /* ref EInvalidValue */
extern TNimType NTI1053; /* EInvalidValue */
extern TFrame* frameptr_12025;
extern tgcheap40616 gch_40645;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}	LA5: ;
	raiseOverflow();	BeforeRet: ;	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_12025;
	frameptr_12025 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_12025 = (*frameptr_12025).prev;
}
static N_INLINE(tcell38448*, usrtocell_42039)(void* usr) {
	tcell38448* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	result = ((tcell38448*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38448))))));
	popFrame();
	return result;
}
static N_INLINE(void, rtladdzct_43602)(tcell38448* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(197, "gc.nim");
	addzct_42015(&gch_40645.Zct, c);	popFrame();
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38448* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(231, "gc.nim");
	c = usrtocell_42039(p);
	nimln(233, "gc.nim");
	{
		nimln(165, "gc.nim");
		(*c).Refcount -= 8;
		nimln(166, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(234, "gc.nim");
		rtladdzct_43602(c);	}	LA3: ;
	popFrame();
}
N_NOINLINE(void, invalidformatstring_126823)(void) {
	einvalidvalue1053* e_126827;
	NimStringDesc* LOC1;
	nimfr("invalidFormatString", "strutils.nim")
	e_126827 = 0;
	nimln(1821, "system.nim");
	e_126827 = (einvalidvalue1053*) newObj((&NTI16601), sizeof(einvalidvalue1053));
	(*e_126827).Sup.Sup.Sup.m_type = (&NTI1053);
	nimln(1822, "system.nim");
	LOC1 = 0;
	LOC1 = (*e_126827).Sup.Sup.message; (*e_126827).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP228));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(1108, "strutils.nim");
	raiseException((E_Base*)e_126827, "EInvalidValue");
	popFrame();
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));	(*dest).Sup.len += (*src).Sup.len;
}
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}	LA5: ;
	raiseOverflow();	BeforeRet: ;	return result;
}
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));	}	LA1: ;
	BeforeRet: ;	return result;
}
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(52, "strutils.nim");
	{
		NI TMP235;
		nimln(730, "system.nim");
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(53, "strutils.nim");
		nimln(53, "strutils.nim");
		nimln(53, "strutils.nim");
		nimln(53, "strutils.nim");
		TMP235 = addInt(((NI) (((NU8)(c)))), 32);
		result = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP235), 0, 255))));
	}	goto LA1;
	LA3: ;
	{
		nimln(55, "strutils.nim");
		result = c;
	}	LA1: ;
	popFrame();
	return result;
}
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	nimfr("cmpIgnoreStyle", "strutils.nim")
	result = 0;
	i = 0;
	j = 0;
	while (1) {
		NIM_CHAR aa;
		NIM_CHAR bb;
		while (1) {
			if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA2;
			i += 1;
		} LA2: ;
		while (1) {
			if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA3;
			j += 1;
		} LA3: ;
		aa = nsuToLowerChar(a->data[i]);
		bb = nsuToLowerChar(b->data[j]);
		result = (NI64)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
		{
			NIM_BOOL LOC6;
			LOC6 = 0;
			LOC6 = !((result == 0));
			if (LOC6) goto LA7;
			LOC6 = ((NU8)(aa) == (NU8)(0));
			LA7: ;
			if (!LOC6) goto LA8;
			goto LA1;
		}		LA8: ;
		i += 1;
		j += 1;
	} LA1: ;
	popFrame();
	return result;
}
N_NIMCALL(NI, findnormalized_126802)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	nimfr("findNormalized", "strutils.nim")
	result = 0;
	nimln(1100, "strutils.nim");
	i = 0;
	nimln(1101, "strutils.nim");
	while (1) {
		nimln(1101, "strutils.nim");
		nimln(1101, "strutils.nim");
		if (!(i < (inarrayLen0-1))) goto LA1;
		nimln(1102, "strutils.nim");
		{
			NI LOC4;
			nimln(1102, "strutils.nim");
			nimln(1102, "strutils.nim");
			if ((NU)(i) >= (NU)(inarrayLen0)) raiseIndexError();
			LOC4 = 0;
			LOC4 = nsuCmpIgnoreStyle(x, inarray[i]);
			if (!(LOC4 == 0)) goto LA5;
			nimln(1102, "strutils.nim");
			nimln(1102, "strutils.nim");
			result = i;
			goto BeforeRet;
		}		LA5: ;
		nimln(1103, "strutils.nim");
		i = addInt(i, 2);
	} LA1: ;
	nimln(1105, "strutils.nim");
	nimln(1105, "strutils.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	nimfr("addf", "strutils.nim")
	nimln(1114, "strutils.nim");
	i = 0;
	nimln(1115, "strutils.nim");
	num = 0;
	nimln(1116, "strutils.nim");
	while (1) {
		nimln(1116, "strutils.nim");
		nimln(1116, "strutils.nim");
		if (!(i < formatstr->Sup.len)) goto LA1;
		nimln(1117, "strutils.nim");
		{
			NI TMP227;
			nimln(1117, "strutils.nim");
			if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
			if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA4;
			nimln(1118, "strutils.nim");
			nimln(1118, "strutils.nim");
			TMP227 = addInt(i, 1);
			if ((NU)((NI64)(TMP227)) > (NU)(formatstr->Sup.len)) raiseIndexError();
			switch (((NU8)(formatstr->data[(NI64)(TMP227)]))) {
			case 35:
			{
				nimln(1121, "strutils.nim");
				{
					nimln(1202, "system.nim");
					nimln(1121, "strutils.nim");
					if (!((NU64)((aLen0-1)) < (NU64)(num))) goto LA9;
					nimln(1121, "strutils.nim");
					invalidformatstring_126823();				}				LA9: ;
				nimln(1122, "strutils.nim");
				if ((NU)(num) >= (NU)(aLen0)) raiseIndexError();
				(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
				nimln(1123, "strutils.nim");
				i = addInt(i, 2);
				nimln(1124, "strutils.nim");
				num = addInt(num, 1);
			}			break;
			case 36:
			{
				nimln(1126, "strutils.nim");
				(*s) = addChar((*s), 36);
				nimln(1127, "strutils.nim");
				i = addInt(i, 2);
			}			break;
			case 49 ... 57:
			case 45:
			{
				NI j;
				NIM_BOOL negative;
				NI idx;
				nimln(1129, "strutils.nim");
				j = 0;
				nimln(1130, "strutils.nim");
				i = addInt(i, 1);
				nimln(1131, "strutils.nim");
				nimln(1131, "strutils.nim");
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
				nimln(1132, "strutils.nim");
				{
					if (!negative) goto LA15;
					nimln(1132, "strutils.nim");
					i = addInt(i, 1);
				}				LA15: ;
				nimln(1133, "strutils.nim");
				while (1) {
					NI TMP229;
					NI TMP230;
					NI TMP231;
					nimln(730, "system.nim");
					if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
					if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA17;
					nimln(1134, "strutils.nim");
					nimln(1134, "strutils.nim");
					nimln(1134, "strutils.nim");
					nimln(1134, "strutils.nim");
					TMP229 = mulInt(j, 10);
					nimln(1134, "strutils.nim");
					if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
					TMP230 = addInt((NI64)(TMP229), ((NI) (((NU8)(formatstr->data[i])))));
					TMP231 = subInt((NI64)(TMP230), 48);
					j = (NI64)(TMP231);
					nimln(1135, "strutils.nim");
					i = addInt(i, 1);
				} LA17: ;
				nimln(1136, "strutils.nim");
				nimln(1136, "strutils.nim");
				{
					NI TMP232;
					nimln(1136, "strutils.nim");
					if (!!(negative)) goto LA20;
					nimln(1136, "strutils.nim");
					TMP232 = subInt(j, 1);
					idx = (NI64)(TMP232);
				}				goto LA18;
				LA20: ;
				{
					NI TMP233;
					nimln(1136, "strutils.nim");
					nimln(1136, "strutils.nim");
					TMP233 = subInt(aLen0, j);
					idx = (NI64)(TMP233);
				}				LA18: ;
				nimln(1137, "strutils.nim");
				{
					nimln(1202, "system.nim");
					nimln(1137, "strutils.nim");
					if (!((NU64)((aLen0-1)) < (NU64)(idx))) goto LA25;
					nimln(1137, "strutils.nim");
					invalidformatstring_126823();				}				LA25: ;
				nimln(1138, "strutils.nim");
				if ((NU)(idx) >= (NU)(aLen0)) raiseIndexError();
				(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
			}			break;
			case 123:
			{
				NI j;
				NI TMP234;
				NI x;
				NI TMP236;
				NI TMP237;
				NimStringDesc* LOC29;
				NI TMP239;
				nimln(1140, "strutils.nim");
				nimln(1140, "strutils.nim");
				TMP234 = addInt(i, 1);
				j = (NI64)(TMP234);
				nimln(1141, "strutils.nim");
				while (1) {
					nimln(731, "system.nim");
					nimln(731, "system.nim");
					if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
					if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA28;
					nimln(1141, "strutils.nim");
					j = addInt(j, 1);
				} LA28: ;
				nimln(1142, "strutils.nim");
				nimln(1142, "strutils.nim");
				nimln(1142, "strutils.nim");
				TMP236 = addInt(i, 2);
				nimln(1142, "strutils.nim");
				TMP237 = subInt(j, 1);
				LOC29 = 0;
				LOC29 = copyStrLast(formatstr, (NI64)(TMP236), (NI64)(TMP237));
				x = findnormalized_126802(LOC29, a, aLen0);
				nimln(1143, "strutils.nim");
				{
					NIM_BOOL LOC32;
					NI TMP238;
					nimln(1143, "strutils.nim");
					LOC32 = 0;
					nimln(702, "system.nim");
					LOC32 = (0 <= x);
					if (!(LOC32)) goto LA33;
					nimln(1143, "strutils.nim");
					nimln(1143, "strutils.nim");
					LOC32 = (x < (aLen0-1));
					LA33: ;
					if (!LOC32) goto LA34;
					nimln(1143, "strutils.nim");
					nimln(1143, "strutils.nim");
					TMP238 = addInt(x, 1);
					if ((NU)((NI64)(TMP238)) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[(NI64)(TMP238)]->Sup.len + 0);
appendString((*s), a[(NI64)(TMP238)]);
				}				goto LA30;
				LA34: ;
				{
					nimln(1144, "strutils.nim");
					invalidformatstring_126823();				}				LA30: ;
				nimln(1145, "strutils.nim");
				nimln(1145, "strutils.nim");
				TMP239 = addInt(j, 1);
				i = (NI64)(TMP239);
			}			break;
			case 97 ... 122:
			case 65 ... 90:
			case 128 ... 255:
			case 95:
			{
				NI j;
				NI TMP240;
				NI x;
				NI TMP241;
				NI TMP242;
				NimStringDesc* LOC39;
				nimln(1147, "strutils.nim");
				nimln(1147, "strutils.nim");
				TMP240 = addInt(i, 1);
				j = (NI64)(TMP240);
				nimln(1148, "strutils.nim");
				while (1) {
					nimln(730, "system.nim");
					if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
					if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA38;
					nimln(1148, "strutils.nim");
					j = addInt(j, 1);
				} LA38: ;
				nimln(1149, "strutils.nim");
				nimln(1149, "strutils.nim");
				nimln(1149, "strutils.nim");
				TMP241 = addInt(i, 1);
				nimln(1149, "strutils.nim");
				TMP242 = subInt(j, 1);
				LOC39 = 0;
				LOC39 = copyStrLast(formatstr, (NI64)(TMP241), (NI64)(TMP242));
				x = findnormalized_126802(LOC39, a, aLen0);
				nimln(1150, "strutils.nim");
				{
					NIM_BOOL LOC42;
					NI TMP243;
					nimln(1150, "strutils.nim");
					LOC42 = 0;
					nimln(702, "system.nim");
					LOC42 = (0 <= x);
					if (!(LOC42)) goto LA43;
					nimln(1150, "strutils.nim");
					nimln(1150, "strutils.nim");
					LOC42 = (x < (aLen0-1));
					LA43: ;
					if (!LOC42) goto LA44;
					nimln(1150, "strutils.nim");
					nimln(1150, "strutils.nim");
					TMP243 = addInt(x, 1);
					if ((NU)((NI64)(TMP243)) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[(NI64)(TMP243)]->Sup.len + 0);
appendString((*s), a[(NI64)(TMP243)]);
				}				goto LA40;
				LA44: ;
				{
					nimln(1151, "strutils.nim");
					invalidformatstring_126823();				}				LA40: ;
				nimln(1152, "strutils.nim");
				i = j;
			}			break;
			default:
			{
				nimln(1154, "strutils.nim");
				invalidformatstring_126823();			}			break;
			}
		}		goto LA2;
		LA4: ;
		{
			nimln(1156, "strutils.nim");
			if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
			(*s) = addChar((*s), formatstr->data[i]);
			nimln(1157, "strutils.nim");
			i = addInt(i, 1);
		}		LA2: ;
	} LA1: ;
	popFrame();
}
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a) {
	NimStringDesc* result;
	NI TMP226;
	TY142070 LOC1;
	nimfr("%", "strutils.nim")
	result = 0;
	nimln(1205, "strutils.nim");
	nimln(1205, "strutils.nim");
	nimln(1205, "strutils.nim");
	nimln(1205, "strutils.nim");
	nimln(1205, "strutils.nim");
	TMP226 = addInt(formatstr->Sup.len, a->Sup.len);
	result = rawNewString((NI64)(TMP226));
	nimln(1206, "strutils.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = copyString(a);
	nsuAddf(&result, formatstr, LOC1, 1);	popFrame();
	return result;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	NI i_124717;
	NI HEX3Atmp_124719;
	NI TMP245;
	NI res_124721;
	nimfr("intToStr", "strutils.nim")
	result = 0;
	nimln(341, "strutils.nim");
	nimln(341, "strutils.nim");
	nimln(341, "strutils.nim");
	if (x == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
	result = nimIntToStr((NI64)abs(x));
	i_124717 = 0;
	HEX3Atmp_124719 = 0;
	nimln(342, "strutils.nim");
	nimln(342, "strutils.nim");
	nimln(342, "strutils.nim");
	TMP245 = subInt(minchars, result->Sup.len);
	HEX3Atmp_124719 = (NI64)(TMP245);
	nimln(1300, "system.nim");
	res_124721 = 1;
	nimln(1301, "system.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(1301, "system.nim");
		if (!(res_124721 <= HEX3Atmp_124719)) goto LA1;
		nimln(1300, "system.nim");
		i_124717 = res_124721;
		nimln(343, "strutils.nim");
		nimln(343, "strutils.nim");
		LOC2 = 0;
		LOC2 = rawNewString(result->Sup.len + 1);
appendChar(LOC2, 48);
appendString(LOC2, result);
		result = LOC2;
		nimln(1303, "system.nim");
		res_124721 = addInt(res_124721, 1);
	} LA1: ;
	nimln(344, "strutils.nim");
	{
		NimStringDesc* LOC7;
		nimln(344, "strutils.nim");
		if (!(x < 0)) goto LA5;
		nimln(345, "strutils.nim");
		nimln(345, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(result->Sup.len + 1);
appendChar(LOC7, 45);
appendString(LOC7, result);
		result = LOC7;
	}	LA5: ;
	popFrame();
	return result;
}N_NOINLINE(void, purestrutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

N_NOINLINE(void, purestrutilsDatInit)(void) {
}

