/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rnentjes/Programming/nimrod/linux-x86_64/f30848148985/lib -o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/pure_dynlib.o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/pure_dynlib.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <dlfcn.h>
typedef struct einvalidlibrary1037 einvalidlibrary1037;
typedef struct eos1035 eos1035;
typedef struct esystem1031 esystem1031;
typedef struct esynch1029 esynch1029;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell38448 tcell38448;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tgcheap40616 tgcheap40616;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion22210 tmemregion22210;
typedef struct tsmallchunk21438 tsmallchunk21438;
typedef struct tllchunk22204 tllchunk22204;
typedef struct tbigchunk21440 tbigchunk21440;
typedef struct tintset21415 tintset21415;
typedef struct ttrunk21411 ttrunk21411;
typedef struct tavlnode22208 tavlnode22208;
typedef struct tgcstat40614 tgcstat40614;
typedef struct tbasechunk21436 tbasechunk21436;
typedef struct tfreecell21428 tfreecell21428;
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct E_Base {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct esynch1029 {
  E_Base Sup;
};
struct esystem1031 {
  esynch1029 Sup;
};
struct eos1035 {
  esystem1031 Sup;
};
struct einvalidlibrary1037 {
  eos1035 Sup;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21438* TY22222[512];
typedef ttrunk21411* ttrunkbuckets21413[256];
struct tintset21415 {
ttrunkbuckets21413 Data;
};
struct tmemregion22210 {
NI Minlargeobj;
NI Maxlargeobj;
TY22222 Freesmallchunks;
tllchunk22204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21440* Freechunkslist;
tintset21415 Chunkstarts;
tavlnode22208* Root;
tavlnode22208* Deleted;
tavlnode22208* Last;
tavlnode22208* Freeavlnodes;
};
struct tgcstat40614 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40616 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
NI64 Maxpause;
tmemregion22210 Region;
tgcstat40614 Stat;
};
typedef NI TY21418[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21418 Bits;
};
struct tbasechunk21436 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21438 {
  tbasechunk21436 Sup;
tsmallchunk21438* Next;
tsmallchunk21438* Prev;
tfreecell21428* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk22204 {
NI Size;
NI Acc;
tllchunk22204* Next;
};
struct tbigchunk21440 {
  tbasechunk21436 Sup;
tbigchunk21440* Next;
tbigchunk21440* Prev;
NI Align;
NF Data;
};
struct ttrunk21411 {
ttrunk21411* Next;
NI Key;
TY21418 Bits;
};
typedef tavlnode22208* TY22214[2];
struct tavlnode22208 {
TY22214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21428 {
tfreecell21428* Next;
NI Zerofield;
};
N_NOINLINE(void, raiseinvalidlibrary_93419)(NCSTRING name);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38448*, usrtocell_42039)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_43602)(tcell38448* c);
N_NOINLINE(void, addzct_42015)(tcellseq38464* s, tcell38448* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(void*, checkedsymaddr_93444)(void* lib, NCSTRING name);
N_NIMCALL(void*, loadlib_93408)(NimStringDesc* path);
N_NIMCALL(void*, loadlib_93412)(void);
N_NIMCALL(void, unloadlib_93415)(void* lib);
N_NIMCALL(void*, symaddr_93439)(void* lib, NCSTRING name);
STRING_LITERAL(TMP146, "could not find symbol: ", 23);
extern TNimType NTI93422; /* ref EInvalidLibrary */
extern TNimType NTI1037; /* EInvalidLibrary */
extern TFrame* frameptr_12025;
extern tgcheap40616 gch_40645;

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));	(*dest).Sup.len += (*src).Sup.len;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_12025;
	frameptr_12025 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_12025 = (*frameptr_12025).prev;
}
static N_INLINE(tcell38448*, usrtocell_42039)(void* usr) {
	tcell38448* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	result = ((tcell38448*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38448))))));
	popFrame();
	return result;
}
static N_INLINE(void, rtladdzct_43602)(tcell38448* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(197, "gc.nim");
	addzct_42015(&gch_40645.Zct, c);	popFrame();
}
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(249, "gc.nim");
	{
		tcell38448* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(250, "gc.nim");
		c = usrtocell_42039(src);
		nimln(167, "gc.nim");
		(*c).Refcount += 8;
	}	LA3: ;
	nimln(252, "gc.nim");
	{
		tcell38448* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(253, "gc.nim");
		c = usrtocell_42039((*dest));
		nimln(254, "gc.nim");
		{
			nimln(165, "gc.nim");
			(*c).Refcount -= 8;
			nimln(166, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(255, "gc.nim");
			rtladdzct_43602(c);		}		LA11: ;
	}	LA7: ;
	nimln(256, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NOINLINE(void, raiseinvalidlibrary_93419)(NCSTRING name) {
	einvalidlibrary1037* e;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("raiseInvalidLibrary", "dynlib.nim")
	e = 0;
	nimln(31, "dynlib.nim");
	e = (einvalidlibrary1037*) newObj((&NTI93422), sizeof(einvalidlibrary1037));
	(*e).Sup.Sup.Sup.Sup.Sup.m_type = (&NTI1037);
	nimln(32, "dynlib.nim");
	nimln(32, "dynlib.nim");
	LOC1 = 0;
	nimln(32, "dynlib.nim");
	LOC2 = 0;
	LOC2 = cstrToNimstr(name);
	LOC1 = rawNewString(LOC2->Sup.len + 23);
appendString(LOC1, ((NimStringDesc*) &TMP146));
appendString(LOC1, LOC2);
	asgnRefNoCycle((void**) &(*e).Sup.Sup.Sup.Sup.message, LOC1);
	nimln(33, "dynlib.nim");
	raiseException((E_Base*)e, "EInvalidLibrary");
	popFrame();
}
N_NIMCALL(void*, checkedsymaddr_93444)(void* lib, NCSTRING name) {
	void* result;
	nimfr("checkedSymAddr", "dynlib.nim")
	result = 0;
	nimln(42, "dynlib.nim");
	result = symaddr_93439(lib, name);
	nimln(43, "dynlib.nim");
	{
		nimln(43, "dynlib.nim");
		if (!(result == NIM_NIL)) goto LA3;
		nimln(43, "dynlib.nim");
		raiseinvalidlibrary_93419(name);	}	LA3: ;
	popFrame();
	return result;
}
N_NIMCALL(void*, loadlib_93408)(NimStringDesc* path) {
	void* result;
	nimfr("LoadLib", "dynlib.nim")
	result = 0;
	nimln(63, "dynlib.nim");
	nimln(63, "dynlib.nim");
	result = dlopen(path->data, RTLD_NOW);
	goto BeforeRet;
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(void*, loadlib_93412)(void) {
	void* result;
	nimfr("LoadLib", "dynlib.nim")
	result = 0;
	nimln(64, "dynlib.nim");
	nimln(64, "dynlib.nim");
	result = dlopen(NIM_NIL, RTLD_NOW);
	goto BeforeRet;
	BeforeRet: ;	popFrame();
	return result;
}
N_NIMCALL(void, unloadlib_93415)(void* lib) {
	nimfr("UnloadLib", "dynlib.nim")
	nimln(65, "dynlib.nim");
	dlclose(lib);	popFrame();
}
N_NIMCALL(void*, symaddr_93439)(void* lib, NCSTRING name) {
	void* result;
	nimfr("symAddr", "dynlib.nim")
	result = 0;
	nimln(67, "dynlib.nim");
	nimln(67, "dynlib.nim");
	result = dlsym(lib, name);
	goto BeforeRet;
	BeforeRet: ;	popFrame();
	return result;
}N_NOINLINE(void, puredynlibInit)(void) {
	nimfr("dynlib", "dynlib.nim")
	popFrame();
}

N_NOINLINE(void, puredynlibDatInit)(void) {
}

