/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rnentjes/Programming/nimrod/linux-x86_64/f30848148985/lib -o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/triangle_glfw.o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/triangle_glfw.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_STDCALL_PTR(double, TY77777) (void);
typedef N_STDCALL_PTR(int, TY77606) (void);
typedef N_STDCALL_PTR(void, TY77635) (int target, int hint);
typedef N_STDCALL_PTR(int, TY77623) (int width, int height, int redbits, int greenbits, int bluebits, int alphabits, int depthbits, int stencilbits, int mode);
typedef N_STDCALL_PTR(void, TY77609) (void);
typedef N_STDCALL_PTR(void, TY77673) (int interval);
typedef N_STDCALL_PTR(void, TY77643) (NCSTRING title);
typedef N_STDCALL_PTR(void, TY77670) (void);
typedef N_STDCALL_PTR(int, TY77710) (int key);
typedef N_STDCALL_PTR(int, TY77677) (int param);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP223, "libglfw.so", 10);
STRING_LITERAL(TMP224, "libglfw.so", 10);
static void* TMP222;
TY77777 Dl_77776;
TY77606 Dl_77605;
TY77635 Dl_77634;
TY77623 Dl_77622;
TY77609 Dl_77608;
TY77673 Dl_77672;
TY77643 Dl_77642;
TY77670 Dl_77669;
TY77710 Dl_77709;
TY77677 Dl_77676;
extern TFrame* frameptr_12025;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_12025;
	frameptr_12025 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_12025 = (*frameptr_12025).prev;
}N_NOINLINE(void, triangleglfwInit)(void) {
	nimfr("glfw", "glfw.nim")
	popFrame();
}

N_NOINLINE(void, triangleglfwDatInit)(void) {
if (!((TMP222 = nimLoadLibrary((NimStringDesc*) &TMP223))
)) nimLoadLibraryError((NimStringDesc*) &TMP224);
	Dl_77776 = (TY77777) nimGetProcAddr(TMP222, "glfwGetTime");
	Dl_77605 = (TY77606) nimGetProcAddr(TMP222, "glfwInit");
	Dl_77634 = (TY77635) nimGetProcAddr(TMP222, "glfwOpenWindowHint");
	Dl_77622 = (TY77623) nimGetProcAddr(TMP222, "glfwOpenWindow");
	Dl_77608 = (TY77609) nimGetProcAddr(TMP222, "glfwTerminate");
	Dl_77672 = (TY77673) nimGetProcAddr(TMP222, "glfwSwapInterval");
	Dl_77642 = (TY77643) nimGetProcAddr(TMP222, "glfwSetWindowTitle");
	Dl_77669 = (TY77670) nimGetProcAddr(TMP222, "glfwSwapBuffers");
	Dl_77709 = (TY77710) nimGetProcAddr(TMP222, "glfwGetKey");
	Dl_77676 = (TY77677) nimGetProcAddr(TMP222, "glfwGetWindowParam");
}

