/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rnentjes/Programming/nimrod/linux-x86_64/f30848148985/lib -o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/triangle_triangle.o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/triangle_triangle.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tgcheap40616 tgcheap40616;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tcell38448 tcell38448;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion22210 tmemregion22210;
typedef struct tsmallchunk21438 tsmallchunk21438;
typedef struct tllchunk22204 tllchunk22204;
typedef struct tbigchunk21440 tbigchunk21440;
typedef struct tintset21415 tintset21415;
typedef struct ttrunk21411 ttrunk21411;
typedef struct tavlnode22208 tavlnode22208;
typedef struct tgcstat40614 tgcstat40614;
typedef struct TNimType TNimType;
typedef struct tbasechunk21436 tbasechunk21436;
typedef struct tfreecell21428 tfreecell21428;
typedef struct TNimNode TNimNode;
typedef N_STDCALL_PTR(void, TY104296) (NI32 x, NI32 y, NI32 width, NI32 height);
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_STDCALL_PTR(NI, TY106846) (NU32 shadertype);
typedef NimStringDesc* TY142070[1];
typedef N_STDCALL_PTR(void, TY106993) (NI shaderobj, NI32 count, NCSTRING* string, NI32* lengths);
typedef N_STDCALL_PTR(void, TY106839) (NI shaderobj);
typedef N_STDCALL_PTR(void, TY106924) (NI shaderobj, NU32 pname, NI32* params);
typedef N_STDCALL_PTR(void, TY106930) (NI shaderobj, NI32 maxlength, NI32* len, NCSTRING infolog);
typedef N_STDCALL_PTR(void, TY104133) (NF32 red, NF32 green, NF32 blue, NF32 alpha);
typedef N_STDCALL_PTR(NI, TY106843) (void);
typedef N_STDCALL_PTR(void, TY106828) (NI programobj, NI shaderobj);
typedef N_STDCALL_PTR(void, TY106989) (NI programobj);
typedef N_STDCALL_PTR(void, TY106910) (NI programobj, NU32 pname, NI32* params);
typedef N_STDCALL_PTR(void, TY107000) (NI programobj);
typedef N_STDCALL_PTR(NI32, TY106905) (NI programobj, NCSTRING char_106907);
typedef N_STDCALL_PTR(void, TY106867) (NU32 index);
typedef NF32 TY142108[9];
typedef N_STDCALL_PTR(void, TY106748) (NI32 n, int* buffers);
typedef N_STDCALL_PTR(void, TY106738) (NU32 target, NU32 buffer);
typedef N_STDCALL_PTR(void, TY106757) (NU32 target, NI32 size, void* data, NU32 usage);
typedef N_STDCALL_PTR(double, TY77777) (void);
typedef N_STDCALL_PTR(int, TY77606) (void);
typedef N_STDCALL_PTR(void, TY77635) (int target, int hint);
typedef N_STDCALL_PTR(int, TY77623) (int width, int height, int redbits, int greenbits, int bluebits, int alphabits, int depthbits, int stencilbits, int mode);
typedef N_STDCALL_PTR(void, TY77609) (void);
typedef N_STDCALL_PTR(void, TY77673) (int interval);
typedef N_STDCALL_PTR(void, TY77643) (NCSTRING title);
typedef N_STDCALL_PTR(void, TY104129) (NU32 mask);
typedef N_STDCALL_PTR(void, TY107330) (NU32 index, NI32 size, NU32 typ, NIM_BOOL normalized, NI32 stride, void* pointer);
typedef N_STDCALL_PTR(void, TY104303) (NU32 mode, NI32 first, NI32 count);
typedef N_STDCALL_PTR(void, TY77670) (void);
typedef N_STDCALL_PTR(int, TY77710) (int key);
typedef N_STDCALL_PTR(int, TY77677) (int param);
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21438* TY22222[512];
typedef ttrunk21411* ttrunkbuckets21413[256];
struct tintset21415 {
ttrunkbuckets21413 Data;
};
struct tmemregion22210 {
NI Minlargeobj;
NI Maxlargeobj;
TY22222 Freesmallchunks;
tllchunk22204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21440* Freechunkslist;
tintset21415 Chunkstarts;
tavlnode22208* Root;
tavlnode22208* Deleted;
tavlnode22208* Last;
tavlnode22208* Freeavlnodes;
};
struct tgcstat40614 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40616 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
NI64 Maxpause;
tmemregion22210 Region;
tgcstat40614 Stat;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
typedef NI TY21418[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21418 Bits;
};
struct tbasechunk21436 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21438 {
  tbasechunk21436 Sup;
tsmallchunk21438* Next;
tsmallchunk21438* Prev;
tfreecell21428* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk22204 {
NI Size;
NI Acc;
tllchunk22204* Next;
};
struct tbigchunk21440 {
  tbasechunk21436 Sup;
tbigchunk21440* Next;
tbigchunk21440* Prev;
NI Align;
NF Data;
};
struct ttrunk21411 {
ttrunk21411* Next;
NI Key;
TY21418 Bits;
};
typedef tavlnode22208* TY22214[2];
struct tavlnode22208 {
TY22214 Link;
NI Key;
NI Upperbound;
NI Level;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct tfreecell21428 {
tfreecell21428* Next;
NI Zerofield;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, resize_142046)(NI32 width, NI32 height);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, loadshader_142053)(NU8 shadertype, NimStringDesc* file);
N_NIMCALL(void, quit_74629)(NimStringDesc* errormsg, NI errorcode);
N_NIMCALL(NimStringDesc*, readfile_9236)(NimStringDesc* filename);
N_NIMCALL(NCSTRING*, alloccstringarray_9601)(NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, dealloccstringarray_9640)(NCSTRING* a);
N_NOCONV(void*, alloc0_4004)(NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NOCONV(void, dealloc_4011)(void* p);
N_NIMCALL(void, initializegl_142086)(void);
N_NIMCALL(void, initializeshaders_142095)(void);
N_NIMCALL(void, initializebuffers_142106)(void);
N_NIMCALL(void, initialize_142126)(void);
N_NIMCALL(void, write_9259)(FILE* f, NimStringDesc* s);
N_NIMCALL(void, nimLoadProcs0)(void);
N_NIMCALL(void, update_142135)(void);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, render_142154)(void);
N_NIMCALL(void, run_142159)(void);
N_NIMCALL(void, gcstep_65602)(NI us, NIM_BOOL strongadvice);
static N_INLINE(void, gcdisable_6002)(void);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, triangleglfwInit)(void);
N_NOINLINE(void, triangleglfwDatInit)(void);
N_NOINLINE(void, coreunsignedInit)(void);
N_NOINLINE(void, coreunsignedDatInit)(void);
N_NOINLINE(void, x11xInit)(void);
N_NOINLINE(void, x11xDatInit)(void);
N_NOINLINE(void, x11xlibInit)(void);
N_NOINLINE(void, x11xlibDatInit)(void);
N_NOINLINE(void, x11keysymInit)(void);
N_NOINLINE(void, x11keysymDatInit)(void);
N_NOINLINE(void, x11xutilInit)(void);
N_NOINLINE(void, x11xutilDatInit)(void);
N_NOINLINE(void, puredynlibInit)(void);
N_NOINLINE(void, puredynlibDatInit)(void);
N_NOINLINE(void, openglopenglInit)(void);
N_NOINLINE(void, openglopenglDatInit)(void);
N_NOINLINE(void, pureparseutilsInit)(void);
N_NOINLINE(void, pureparseutilsDatInit)(void);
N_NOINLINE(void, purestrutilsInit)(void);
N_NOINLINE(void, purestrutilsDatInit)(void);
N_NOINLINE(void, coretypeinfoInit)(void);
N_NOINLINE(void, coretypeinfoDatInit)(void);
N_NOINLINE(void, puremathInit)(void);
N_NOINLINE(void, puremathDatInit)(void);
N_NOINLINE(void, triangleInit)(void);
N_NOINLINE(void, triangleDatInit)(void);
STRING_LITERAL(TMP214, "Error compiling shaders! Can\'t get shader handle!", 49);
STRING_LITERAL(TMP215, "Error compiling the shader: ", 28);
STRING_LITERAL(TMP216, " error: ", 8);
STRING_LITERAL(TMP217, "vertexshader.vert", 17);
STRING_LITERAL(TMP218, "fragshader.frag", 15);
STRING_LITERAL(TMP219, "Error compiling shaders! Can\'t get shader handles!", 50);
STRING_LITERAL(TMP220, "Error linking shader program!", 29);
NIM_CONST TY142108 TMP221 = {0.0,
5.0000000000000000e-01,
0.0,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0,
5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0}
;
STRING_LITERAL(TMP225, "Could not initialize GLFW! \012", 28);
STRING_LITERAL(TMP244, "FPS: $1", 7);
NIM_BOOL running_142003;
NI framecount_142004;
NF lasttime_142006;
NF lastfpstime_142008;
NF currenttime_142010;
NI framerate_142011;
NF framedelta_142013;
NI32 windoww_142015;
NI32 windowh_142017;
NI vshaderid_142018;
NI fshaderid_142019;
NI shaderprog_142020;
NU32 vertexposattrloc_142021;
double starttime_142022;
NU32 vbo_142023;
extern TY104296 Dl_104295;
extern TFrame* frameptr_12025;
extern TY106846 Dl_106845;
extern TY106993 Dl_106992;
extern TY106839 Dl_106838;
extern TY106924 Dl_106923;
extern TY106930 Dl_106929;
extern TY104133 Dl_104132;
extern TY106843 Dl_106842;
extern TY106828 Dl_106827;
extern TY106989 Dl_106988;
extern TY106910 Dl_106909;
extern TY107000 Dl_106999;
extern TY106905 Dl_106904;
extern TY106867 Dl_106866;
extern TY106748 Dl_106747;
extern TY106738 Dl_106737;
extern TY106757 Dl_106756;
extern TY77777 Dl_77776;
extern TY77606 Dl_77605;
extern TY77635 Dl_77634;
extern TY77623 Dl_77622;
extern TY77609 Dl_77608;
extern TY77673 Dl_77672;
extern TY77643 Dl_77642;
extern TY104129 Dl_104128;
extern TY107330 Dl_107329;
extern TY104303 Dl_104302;
extern TY77670 Dl_77669;
extern TY77710 Dl_77709;
extern TY77677 Dl_77676;
extern tgcheap40616 gch_40645;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_12025;
	frameptr_12025 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_12025 = (*frameptr_12025).prev;
}
N_NIMCALL(void, resize_142046)(NI32 width, NI32 height) {
	nimfr("Resize", "triangle.nim")
	nimln(40, "triangle.nim");
	Dl_104295(((NI32) 0), ((NI32) 0), width, height);	popFrame();
}
N_NIMCALL(NI, loadshader_142053)(NU8 shadertype, NimStringDesc* file) {
	NI result;
	NimStringDesc* shadersrc;
	NI shader;
	NCSTRING* stringarray;
	TY142070 LOC10;
	NI32 compileresult;
	nimfr("LoadShader", "triangle.nim")
	result = 0;
	nimln(46, "triangle.nim");
	{
		nimln(46, "triangle.nim");
		if (!(shadertype == ((NU8) 0))) goto LA3;
		nimln(47, "triangle.nim");
		result = Dl_106845(((NU32) 35633));
	}	goto LA1;
	LA3: ;
	{
		nimln(50, "triangle.nim");
		result = Dl_106845(((NU32) 35632));
	}	LA1: ;
	nimln(52, "triangle.nim");
	{
		nimln(52, "triangle.nim");
		if (!(result == -1)) goto LA8;
		nimln(53, "triangle.nim");
		quit_74629(((NimStringDesc*) &TMP214), 1);	}	LA8: ;
	nimln(55, "triangle.nim");
	shadersrc = readfile_9236(file);
	nimln(57, "triangle.nim");
	shader = result;
	nimln(59, "triangle.nim");
	memset((void*)LOC10, 0, sizeof(LOC10));
	LOC10[0] = copyString(shadersrc);
	stringarray = alloccstringarray_9601(LOC10, 1);
	nimln(61, "triangle.nim");
	Dl_106992(shader, ((NI32) 1), stringarray, NIM_NIL);	nimln(63, "triangle.nim");
	dealloccstringarray_9640(stringarray);	nimln(65, "triangle.nim");
	Dl_106838(shader);	compileresult = 0;
	nimln(69, "triangle.nim");
	Dl_106923(shader, ((NU32) 35713), &compileresult);	nimln(71, "triangle.nim");
	{
		NI32 loglength;
		NCSTRING log;
		void* LOC15;
		NimStringDesc* LOC16;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((compileresult == ((NI32) 1)))) goto LA13;
		nimln(72, "triangle.nim");
		result = -1;
		loglength = 0;
		nimln(75, "triangle.nim");
		Dl_106923(shader, ((NU32) 35716), &loglength);		nimln(77, "triangle.nim");
		nimln(77, "triangle.nim");
		LOC15 = 0;
		LOC15 = alloc0_4004(((NI) (loglength)));
		log = ((NCSTRING) (LOC15));
		nimln(78, "triangle.nim");
		Dl_106929(shader, loglength, &loglength, log);		nimln(79, "triangle.nim");
		nimln(79, "triangle.nim");
		LOC16 = 0;
		LOC16 = cstrToNimstr(log);
		printf("%s%s%s%s\012", (((NimStringDesc*) &TMP215))->data, (file)->data, (((NimStringDesc*) &TMP216))->data, (LOC16)->data);
		nimln(81, "triangle.nim");
		dealloc_4011(((void*) (log)));	}	LA13: ;
	popFrame();
	return result;
}
N_NIMCALL(void, initializegl_142086)(void) {
	nimfr("InitializeGL", "triangle.nim")
	nimln(87, "triangle.nim");
	Dl_104132(2.0000000000000001e-01, 0.0, 2.0000000000000001e-01, 1.0000000000000000e+00);	popFrame();
}
N_NIMCALL(void, initializeshaders_142095)(void) {
	NI32 linkstatus;
	NI32 LOC11;
	nimfr("InitializeShaders", "triangle.nim")
	nimln(93, "triangle.nim");
	vshaderid_142018 = loadshader_142053(((NU8) 0), ((NimStringDesc*) &TMP217));
	nimln(94, "triangle.nim");
	fshaderid_142019 = loadshader_142053(((NU8) 1), ((NimStringDesc*) &TMP218));
	nimln(96, "triangle.nim");
	{
		NIM_BOOL LOC3;
		nimln(96, "triangle.nim");
		LOC3 = 0;
		nimln(96, "triangle.nim");
		LOC3 = (vshaderid_142018 == -1);
		if (LOC3) goto LA4;
		nimln(96, "triangle.nim");
		LOC3 = (fshaderid_142019 == -1);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(97, "triangle.nim");
		quit_74629(((NimStringDesc*) &TMP219), 1);	}	LA5: ;
	nimln(99, "triangle.nim");
	shaderprog_142020 = Dl_106842();
	nimln(101, "triangle.nim");
	Dl_106827(shaderprog_142020, vshaderid_142018);	nimln(102, "triangle.nim");
	Dl_106827(shaderprog_142020, fshaderid_142019);	nimln(104, "triangle.nim");
	Dl_106988(shaderprog_142020);	linkstatus = 0;
	nimln(108, "triangle.nim");
	Dl_106909(shaderprog_142020, ((NU32) 35714), &linkstatus);	nimln(110, "triangle.nim");
	{
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((linkstatus == ((NI32) 1)))) goto LA9;
		nimln(111, "triangle.nim");
		quit_74629(((NimStringDesc*) &TMP220), 1);	}	LA9: ;
	nimln(113, "triangle.nim");
	Dl_106999(shaderprog_142020);	nimln(115, "triangle.nim");
	nimln(115, "triangle.nim");
	LOC11 = 0;
	LOC11 = Dl_106904(shaderprog_142020, "a_position");
	vertexposattrloc_142021 = ((NU32) (LOC11));
	nimln(117, "triangle.nim");
	Dl_106866(vertexposattrloc_142021);	popFrame();
}
N_NIMCALL(void, initializebuffers_142106)(void) {
	TY142108 vertices;
	nimfr("InitializeBuffers", "triangle.nim")
	nimln(123, "triangle.nim");
	memcpy((void*)vertices, (NIM_CONST void*)TMP221, sizeof(vertices));
	nimln(128, "triangle.nim");
	Dl_106747(((NI32) 1), &vbo_142023);	nimln(130, "triangle.nim");
	Dl_106737(((NU32) 34962), vbo_142023);	nimln(132, "triangle.nim");
	Dl_106756(((NU32) 34962), ((NI32) 36), ((void*) (&vertices[(0)- 0])), ((NU32) 35044));	popFrame();
}
N_NIMCALL(void, initialize_142126)(void) {
	nimfr("Initialize", "triangle.nim")
	nimln(137, "triangle.nim");
	starttime_142022 = Dl_77776();
	nimln(139, "triangle.nim");
	{
		int LOC3;
		nimln(139, "triangle.nim");
		nimln(139, "triangle.nim");
		LOC3 = 0;
		LOC3 = Dl_77605();
		if (!(LOC3 == ((NI32) 0))) goto LA4;
		nimln(140, "triangle.nim");
		write_9259(stdout, ((NimStringDesc*) &TMP225));	}	LA4: ;
	nimln(142, "triangle.nim");
	Dl_77634(((int) 131090), ((int) 0));	nimln(143, "triangle.nim");
	Dl_77634(((int) 139265), ((int) 196610));	nimln(144, "triangle.nim");
	Dl_77634(((int) 131092), ((int) 2));	nimln(145, "triangle.nim");
	Dl_77634(((int) 131093), ((int) 0));	nimln(146, "triangle.nim");
	Dl_77634(((int) 131095), ((int) 1));	nimln(151, "triangle.nim");
	{
		int LOC8;
		nimln(151, "triangle.nim");
		nimln(151, "triangle.nim");
		LOC8 = 0;
		LOC8 = Dl_77622(windoww_142015, windowh_142017, ((int) 0), ((int) 0), ((int) 0), ((int) 0), ((int) 0), ((int) 0), ((int) 65537));
		if (!(LOC8 == ((NI32) 0))) goto LA9;
		nimln(152, "triangle.nim");
		Dl_77608();	}	LA9: ;
	nimln(155, "triangle.nim");
	Dl_77672(((int) 1));	nimln(94, "opengl.nim");
	nimLoadProcs0();	nimln(159, "triangle.nim");
	initializegl_142086();	nimln(161, "triangle.nim");
	resize_142046(windoww_142015, windowh_142017);	nimln(163, "triangle.nim");
	lasttime_142006 = Dl_77776();
	nimln(164, "triangle.nim");
	lastfpstime_142008 = lasttime_142006;
	nimln(166, "triangle.nim");
	initializeshaders_142095();	nimln(167, "triangle.nim");
	initializebuffers_142106();	popFrame();
}
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}	LA5: ;
	raiseOverflow();	BeforeRet: ;	return result;
}
N_NIMCALL(void, update_142135)(void) {
	NF delta;
	nimfr("Update", "triangle.nim")
	nimln(173, "triangle.nim");
	currenttime_142010 = Dl_77776();
	nimln(175, "triangle.nim");
	nimln(175, "triangle.nim");
	framedelta_142013 = ((NF)(currenttime_142010) - (NF)(lasttime_142006));
	nimln(177, "triangle.nim");
	lasttime_142006 = currenttime_142010;
	nimln(179, "triangle.nim");
	{
		NimStringDesc* LOC5;
		NimStringDesc* LOC6;
		nimln(706, "system.nim");
		nimln(179, "triangle.nim");
		if (!(1.0000000000000000e+00 < ((NF)(currenttime_142010) - (NF)(lastfpstime_142008)))) goto LA3;
		nimln(180, "triangle.nim");
		nimln(180, "triangle.nim");
		nimln(180, "triangle.nim");
		framerate_142011 = ((NI) (((NF)(((NF) (framecount_142004))) / (NF)(((NF)(currenttime_142010) - (NF)(lastfpstime_142008))))));
		nimln(181, "triangle.nim");
		nimln(181, "triangle.nim");
		nimln(181, "triangle.nim");
		LOC5 = 0;
		LOC5 = nsuIntToStr(framerate_142011, 1);
		LOC6 = 0;
		LOC6 = nsuFormatSingleElem(((NimStringDesc*) &TMP244), LOC5);
		Dl_77642(LOC6->data);		nimln(183, "triangle.nim");
		lastfpstime_142008 = currenttime_142010;
		nimln(184, "triangle.nim");
		framecount_142004 = 0;
	}	LA3: ;
	nimln(186, "triangle.nim");
	nimln(186, "triangle.nim");
	delta = ((NF)(currenttime_142010) - (NF)(starttime_142022));
	nimln(188, "triangle.nim");
	framecount_142004 = addInt(framecount_142004, 1);
	popFrame();
}
N_NIMCALL(void, render_142154)(void) {
	nimfr("Render", "triangle.nim")
	nimln(194, "triangle.nim");
	Dl_104128(((NU32) 16384));	nimln(196, "triangle.nim");
	Dl_106999(shaderprog_142020);	nimln(198, "triangle.nim");
	Dl_106737(((NU32) 34962), vbo_142023);	nimln(200, "triangle.nim");
	Dl_107329(vertexposattrloc_142021, ((NI32) 3), ((NU32) 5126), NIM_FALSE, ((NI32) 0), NIM_NIL);	nimln(202, "triangle.nim");
	Dl_104302(((NU32) 4), ((NI32) 0), ((NI32) 3));	nimln(204, "triangle.nim");
	Dl_106999(0);	nimln(206, "triangle.nim");
	Dl_77669();	popFrame();
}
N_NIMCALL(void, run_142159)(void) {
	nimfr("Run", "triangle.nim")
	nimln(212, "triangle.nim");
	while (1) {
		NIM_BOOL LOC2;
		int LOC3;
		int LOC5;
		if (!running_142003) goto LA1;
		nimln(214, "triangle.nim");
		update_142135();		nimln(216, "triangle.nim");
		render_142154();		nimln(218, "triangle.nim");
		gcstep_65602(1000, NIM_FALSE);		nimln(220, "triangle.nim");
		nimln(220, "triangle.nim");
		LOC2 = 0;
		nimln(220, "triangle.nim");
		nimln(220, "triangle.nim");
		LOC3 = 0;
		LOC3 = Dl_77709(((int) 257));
		LOC2 = (LOC3 == ((NI32) 0));
		if (!(LOC2)) goto LA4;
		nimln(221, "triangle.nim");
		nimln(221, "triangle.nim");
		LOC5 = 0;
		LOC5 = Dl_77676(((int) 131073));
		LOC2 = (LOC5 == ((NI32) 1));
		LA4: ;
		running_142003 = LOC2;
	} LA1: ;
	popFrame();
}
static N_INLINE(void, gcdisable_6002)(void) {
	nimfr("GC_disable", "gc.nim")
	nimln(1010, "gc.nim");
	gch_40645.Recgclock += 1;
	popFrame();
}
static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);}int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	triangleglfwDatInit();
	coreunsignedDatInit();
	x11xDatInit();
	x11xlibDatInit();
	x11keysymDatInit();
	x11xutilDatInit();
	puredynlibDatInit();
	openglopenglDatInit();
	pureparseutilsDatInit();
	purestrutilsDatInit();
	coretypeinfoDatInit();
	puremathDatInit();
	triangleDatInit();
	initStackBottom();
	systemInit();
	triangleglfwInit();
	coreunsignedInit();
	x11xInit();
	x11xlibInit();
	x11keysymInit();
	x11xutilInit();
	puredynlibInit();
	openglopenglInit();
	pureparseutilsInit();
	purestrutilsInit();
	coretypeinfoInit();
	puremathInit();
	triangleInit();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}
N_NOINLINE(void, triangleInit)(void) {
	nimfr("triangle", "triangle.nim")
	nimln(10, "triangle.nim");
	running_142003 = NIM_TRUE;
	nimln(11, "triangle.nim");
	framecount_142004 = 0;
	nimln(12, "triangle.nim");
	lasttime_142006 = 0.0;
	nimln(13, "triangle.nim");
	lastfpstime_142008 = 0.0;
	nimln(14, "triangle.nim");
	currenttime_142010 = 0.0;
	nimln(15, "triangle.nim");
	framerate_142011 = 0;
	nimln(16, "triangle.nim");
	framedelta_142013 = 0.0;
	nimln(18, "triangle.nim");
	windoww_142015 = ((NI32) 800);
	nimln(19, "triangle.nim");
	windowh_142017 = ((NI32) 400);
	nimln(226, "triangle.nim");
	gcdisable_6002();	nimln(228, "triangle.nim");
	initialize_142126();	nimln(230, "triangle.nim");
	run_142159();	nimln(232, "triangle.nim");
	Dl_77608();	popFrame();
}

N_NOINLINE(void, triangleDatInit)(void) {
}

