/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rnentjes/Programming/nimrod/linux-x86_64/f30848148985/lib -o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/x11_xutil.o /home/rnentjes/Development/nimrod/nimrod-opengl/triangle/nimcache/x11_xutil.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct txclasshint92115 txclasshint92115;
typedef struct txiconsize92111 txiconsize92111;
typedef struct txsizehints92018 txsizehints92018;
typedef struct txstandardcolormap92185 txstandardcolormap92185;
typedef struct txwmhints92058 txwmhints92058;
typedef struct txregion92140 txregion92140;
typedef struct txrectangle80537 txrectangle80537;
typedef struct tdisplay80487 tdisplay80487;
typedef struct txtextproperty92090 txtextproperty92090;
typedef struct txvisualinfo92153 txvisualinfo92153;
typedef struct txkeyevent80577 txkeyevent80577;
typedef struct txcomposestatus92133 txcomposestatus92133;
typedef struct txpoint80533 txpoint80533;
typedef struct txgc80471 txgc80471;
typedef struct tximage80517 tximage80517;
typedef struct tf80515 tf80515;
typedef struct tvisual80479 tvisual80479;
typedef struct tcpoint92014 tcpoint92014;
typedef struct txextdata80455 txextdata80455;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_CDECL_PTR(txclasshint92115*, TY92212) (void);
typedef N_CDECL_PTR(txiconsize92111*, TY92215) (void);
typedef N_CDECL_PTR(txsizehints92018*, TY92218) (void);
typedef N_CDECL_PTR(txstandardcolormap92185*, TY92221) (void);
typedef N_CDECL_PTR(txwmhints92058*, TY92224) (void);
typedef N_CDECL_PTR(int, TY92227) (txregion92140* para1, txrectangle80537* para2);
typedef N_CDECL_PTR(txregion92140*, TY92232) (void);
typedef N_CDECL_PTR(NCSTRING, TY92235) (void);
typedef N_CDECL_PTR(int, TY92238) (tdisplay80487* para1, unsigned long para2, int para3);
typedef N_CDECL_PTR(int, TY92244) (txregion92140* para1);
typedef N_CDECL_PTR(int, TY92248) (txregion92140* para1);
typedef N_CDECL_PTR(int, TY92252) (txregion92140* para1, txregion92140* para2);
typedef N_CDECL_PTR(int, TY92257) (tdisplay80487* para1, unsigned long para2, int para3, NIM_CHAR** para4);
typedef N_CDECL_PTR(int, TY92264) (tdisplay80487* para1, unsigned long para2, txclasshint92115* para3);
typedef N_CDECL_PTR(int, TY92270) (tdisplay80487* para1, unsigned long para2, txiconsize92111** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY92277) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3);
typedef N_CDECL_PTR(int, TY92283) (tdisplay80487* para1, unsigned long para2, txstandardcolormap92185** para3, NI32* para4, unsigned long para5);
typedef N_CDECL_PTR(int, TY92291) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY92298) (tdisplay80487* para1, unsigned long para2, txstandardcolormap92185* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY92305) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3, unsigned long para4);
typedef N_CDECL_PTR(txvisualinfo92153*, TY92312) (tdisplay80487* para1, long para2, txvisualinfo92153* para3, NI32* para4);
typedef N_CDECL_PTR(int, TY92319) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3);
typedef N_CDECL_PTR(txwmhints92058*, TY92325) (tdisplay80487* para1, unsigned long para2);
typedef N_CDECL_PTR(int, TY92330) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3);
typedef N_CDECL_PTR(int, TY92336) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3);
typedef N_CDECL_PTR(int, TY92342) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3, NI* para4);
typedef N_CDECL_PTR(int, TY92350) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3, NI* para4, unsigned long para5);
typedef N_CDECL_PTR(int, TY92359) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3);
typedef N_CDECL_PTR(int, TY92365) (txregion92140* para1, txregion92140* para2, txregion92140* para3);
typedef N_CDECL_PTR(void, TY92371) (unsigned long para1, unsigned long* para2, unsigned long* para3);
typedef N_CDECL_PTR(int, TY92377) (txkeyevent80577* para1, NCSTRING para2, int para3, unsigned long* para4, txcomposestatus92133* para5);
typedef N_CDECL_PTR(int, TY92385) (tdisplay80487* para1, int para2, int para3, int para4, txvisualinfo92153* para5);
typedef N_CDECL_PTR(int, TY92393) (txregion92140* para1, int para2, int para3);
typedef N_CDECL_PTR(NI, TY92399) (txregion92140* para1, int para2, int para3);
typedef N_CDECL_PTR(txregion92140*, TY92405) (txpoint80533* para1, int para2, int para3);
typedef N_CDECL_PTR(int, TY92411) (txregion92140* para1, int para2, int para3, int para4, int para5);
typedef N_CDECL_PTR(int, TY92419) (tdisplay80487* para1, unsigned long para2, int para3, NCSTRING para4);
typedef N_CDECL_PTR(int, TY92426) (tdisplay80487* para1, unsigned long para2, txclasshint92115* para3);
typedef N_CDECL_PTR(int, TY92432) (tdisplay80487* para1, unsigned long para2, txiconsize92111* para3, int para4);
typedef N_CDECL_PTR(int, TY92439) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3);
typedef N_CDECL_PTR(void, TY92445) (tdisplay80487* para1, unsigned long para2, txstandardcolormap92185* para3, int para4, unsigned long para5);
typedef N_CDECL_PTR(int, TY92453) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY92460) (tdisplay80487* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, unsigned long para5, NCSTRING* para6, int para7, txsizehints92018* para8);
typedef N_CDECL_PTR(void, TY92471) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3, unsigned long para4);
typedef N_CDECL_PTR(void, TY92478) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3);
typedef N_CDECL_PTR(int, TY92484) (tdisplay80487* para1, unsigned long para2, txwmhints92058* para3);
typedef N_CDECL_PTR(void, TY92490) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3);
typedef N_CDECL_PTR(void, TY92496) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3);
typedef N_CDECL_PTR(void, TY92502) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3);
typedef N_CDECL_PTR(void, TY92508) (tdisplay80487* para1, unsigned long para2, txtextproperty92090* para3, txtextproperty92090* para4, NCSTRING* para5, int para6, txsizehints92018* para7, txwmhints92058* para8, txclasshint92115* para9);
typedef N_CDECL_PTR(void, TY92520) (tdisplay80487* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, NCSTRING* para5, int para6, txsizehints92018* para7, txwmhints92058* para8, txclasshint92115* para9);
typedef N_CDECL_PTR(void, TY92532) (tdisplay80487* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, NCSTRING* para5, int para6, txsizehints92018* para7, txwmhints92058* para8, txclasshint92115* para9);
typedef N_CDECL_PTR(void, TY92544) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY92551) (tdisplay80487* para1, txgc80471* para2, txregion92140* para3);
typedef N_CDECL_PTR(void, TY92557) (tdisplay80487* para1, unsigned long para2, txstandardcolormap92185* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY92564) (tdisplay80487* para1, unsigned long para2, txsizehints92018* para3);
typedef N_CDECL_PTR(int, TY92570) (txregion92140* para1, int para2, int para3);
typedef N_CDECL_PTR(int, TY92576) (NCSTRING* para1, int para2, txtextproperty92090* para3);
typedef N_CDECL_PTR(int, TY92582) (txregion92140* para1, txregion92140* para2, txregion92140* para3);
typedef N_CDECL_PTR(int, TY92588) (tdisplay80487* para1, NCSTRING* para2, int para3, NU8 para4, txtextproperty92090* para5);
typedef N_CDECL_PTR(int, TY92596) (tdisplay80487* para1, NI16** para2, int para3, NU8 para4, txtextproperty92090* para5);
typedef N_CDECL_PTR(int, TY92606) (tdisplay80487* para1, NCSTRING* para2, int para3, NU8 para4, txtextproperty92090* para5);
typedef N_CDECL_PTR(void, TY92614) (NI16** para1);
typedef N_CDECL_PTR(int, TY92620) (txtextproperty92090* para1, NCSTRING** para2, NI32* para3);
typedef N_CDECL_PTR(int, TY92626) (tdisplay80487* para1, txtextproperty92090* para2, NCSTRING** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY92633) (tdisplay80487* para1, txtextproperty92090* para2, NI16*** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY92643) (tdisplay80487* para1, txtextproperty92090* para2, NCSTRING** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY92650) (txrectangle80537* para1, txregion92140* para2, txregion92140* para3);
typedef N_CDECL_PTR(int, TY92656) (txregion92140* para1, txregion92140* para2, txregion92140* para3);
typedef N_CDECL_PTR(int, TY92662) (tdisplay80487* para1, int para2, NCSTRING para3, NCSTRING para4, int para5, txsizehints92018* para6, NI32* para7, NI32* para8, NI32* para9, NI32* para10, NI32* para11);
typedef N_CDECL_PTR(int, TY92676) (txregion92140* para1, txregion92140* para2, txregion92140* para3);
typedef N_CDECL_PTR(tximage80517*, TY80855) (tdisplay80487* para1, tvisual80479* para2, int para3, int para4, int para5, NCSTRING para6, int para7, int para8, int para9, int para10);
typedef N_CDECL_PTR(int, TY80868) (tximage80517* para1);
typedef N_CDECL_PTR(unsigned long, TY80872) (tximage80517* para1, int para2, int para3);
typedef N_CDECL_PTR(int, TY80878) (tximage80517* para1, int para2, int para3, unsigned long para4);
typedef N_CDECL_PTR(tximage80517*, TY80885) (tximage80517* para1, int para2, int para3, int para4, int para5);
typedef N_CDECL_PTR(int, TY80893) (tximage80517* para1, long para2);
struct tf80515 {
TY80855 Createimage;
TY80868 Destroyimage;
TY80872 Getpixel;
TY80878 Putpixel;
TY80885 Subimage;
TY80893 Addpixel;
};
struct tximage80517 {
int Width;
int Height;
int Xoffset;
int Format;
NCSTRING Data;
int Byteorder;
int Bitmapunit;
int Bitmapbitorder;
int Bitmappad;
int Depth;
int Bytesperline;
int Bitsperpixel;
unsigned long Redmask;
unsigned long Greenmask;
unsigned long Bluemask;
NIM_CHAR* Obdata;
tf80515 F;
};
struct txclasshint92115 {
NCSTRING Resname;
NCSTRING Resclass;
};
struct txiconsize92111 {
int Minwidth;
int Minheight;
int Maxwidth;
int Maxheight;
int Widthinc;
int Heightinc;
};
struct tcpoint92014 {
int X;
int Y;
};
struct txsizehints92018 {
long Flags;
int X;
int Y;
int Width;
int Height;
int Minwidth;
int Minheight;
int Maxwidth;
int Maxheight;
int Widthinc;
int Heightinc;
tcpoint92014 Minaspect;
tcpoint92014 Maxaspect;
int Basewidth;
int Baseheight;
int Wingravity;
};
struct txstandardcolormap92185 {
unsigned long Colormap;
unsigned long Redmax;
unsigned long Redmult;
unsigned long Greenmax;
unsigned long Greenmult;
unsigned long Bluemax;
unsigned long Bluemult;
unsigned long Basepixel;
unsigned long Visualid;
unsigned long Killid;
};
struct txwmhints92058 {
long Flags;
NI Input;
int Initialstate;
unsigned long Iconpixmap;
unsigned long Iconwindow;
int Iconx;
int Icony;
unsigned long Iconmask;
unsigned long Windowgroup;
};
struct txregion92140 {
char dummy;
};
struct txrectangle80537 {
short X;
short Y;
unsigned short Width;
unsigned short Height;
};
struct tdisplay80487 {
char dummy;
};
struct txtextproperty92090 {
NCSTRING Value;
unsigned long Encoding;
int Format;
unsigned long Nitems;
};
struct txvisualinfo92153 {
tvisual80479* Visual;
unsigned long Visualid;
int Screen;
int Depth;
int Class;
unsigned long Redmask;
unsigned long Greenmask;
unsigned long Bluemask;
int Colormapsize;
int Bitsperrgb;
};
struct txkeyevent80577 {
int Thetype;
unsigned long Serial;
NI Sendevent;
tdisplay80487* Display;
unsigned long Window;
unsigned long Root;
unsigned long Subwindow;
unsigned long Time;
int X;
int Y;
int Xroot;
int Yroot;
int State;
int Keycode;
NI Samescreen;
};
struct txcomposestatus92133 {
NIM_CHAR* Composeptr;
int Charsmatched;
};
struct txpoint80533 {
short X;
short Y;
};
struct txgc80471 {
char dummy;
};
struct tvisual80479 {
txextdata80455* Extdata;
unsigned long Visualid;
int Cclass;
unsigned long Redmask;
unsigned long Greenmask;
unsigned long Bluemask;
int Bitsperrgb;
int Mapentries;
};
typedef N_CDECL_PTR(int, TY80740) (txextdata80455* extension);
struct txextdata80455 {
int Number;
txextdata80455* Next;
TY80740 Freeprivate;
NIM_CHAR* Privatedata;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(int, xdestroyimage_92682)(tximage80517* ximage);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(unsigned long, xgetpixel_92686)(tximage80517* ximage, int x, int y);
N_NIMCALL(int, xputpixel_92692)(tximage80517* ximage, int x, int y, unsigned long pixel);
N_NIMCALL(tximage80517*, xsubimage_92699)(tximage80517* ximage, int x, int y, int width, int height);
N_NIMCALL(int, xaddpixel_92707)(tximage80517* ximage, long value);
N_NIMCALL(NIM_BOOL, iskeypadkey_92712)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, isprivatekeypadkey_92716)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, iscursorkey_92720)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, ispfkey_92724)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, isfunctionkey_92728)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, ismiscfunctionkey_92732)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, ismodifierkey_92736)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_79066)(unsigned long a, unsigned long b);
STRING_LITERAL(TMP141, "libX11.so", 9);
STRING_LITERAL(TMP142, "libX11.so", 9);
static void* TMP140;
TY92212 Dl_92211;
TY92215 Dl_92214;
TY92218 Dl_92217;
TY92221 Dl_92220;
TY92224 Dl_92223;
TY92227 Dl_92226;
TY92232 Dl_92231;
TY92235 Dl_92234;
TY92238 Dl_92237;
TY92244 Dl_92243;
TY92248 Dl_92247;
TY92252 Dl_92251;
TY92257 Dl_92256;
TY92264 Dl_92263;
TY92270 Dl_92269;
TY92277 Dl_92276;
TY92283 Dl_92282;
TY92291 Dl_92290;
TY92298 Dl_92297;
TY92305 Dl_92304;
TY92312 Dl_92311;
TY92319 Dl_92318;
TY92325 Dl_92324;
TY92330 Dl_92329;
TY92336 Dl_92335;
TY92342 Dl_92341;
TY92350 Dl_92349;
TY92359 Dl_92358;
TY92365 Dl_92364;
TY92371 Dl_92370;
TY92377 Dl_92376;
TY92385 Dl_92384;
TY92393 Dl_92392;
TY92399 Dl_92398;
TY92405 Dl_92404;
TY92411 Dl_92410;
TY92419 Dl_92418;
TY92426 Dl_92425;
TY92432 Dl_92431;
TY92439 Dl_92438;
TY92445 Dl_92444;
TY92453 Dl_92452;
TY92460 Dl_92459;
TY92471 Dl_92470;
TY92478 Dl_92477;
TY92484 Dl_92483;
TY92490 Dl_92489;
TY92496 Dl_92495;
TY92502 Dl_92501;
TY92508 Dl_92507;
TY92520 Dl_92519;
TY92532 Dl_92531;
TY92544 Dl_92543;
TY92551 Dl_92550;
TY92557 Dl_92556;
TY92564 Dl_92563;
TY92570 Dl_92569;
TY92576 Dl_92575;
TY92582 Dl_92581;
TY92588 Dl_92587;
TY92596 Dl_92595;
TY92606 Dl_92605;
TY92614 Dl_92613;
TY92620 Dl_92619;
TY92626 Dl_92625;
TY92633 Dl_92632;
TY92643 Dl_92642;
TY92650 Dl_92649;
TY92656 Dl_92655;
TY92662 Dl_92661;
TY92676 Dl_92675;
extern TFrame* frameptr_12025;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_12025;
	frameptr_12025 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_12025 = (*frameptr_12025).prev;
}
N_NIMCALL(int, xdestroyimage_92682)(tximage80517* ximage) {
	int result;
	nimfr("XDestroyImage", "xutil.nim")
	result = 0;
	nimln(378, "xutil.nim");
	result = (*ximage).F.Destroyimage(ximage);
	popFrame();
	return result;
}
N_NIMCALL(unsigned long, xgetpixel_92686)(tximage80517* ximage, int x, int y) {
	unsigned long result;
	nimfr("XGetPixel", "xutil.nim")
	result = 0;
	nimln(381, "xutil.nim");
	result = (*ximage).F.Getpixel(ximage, x, y);
	popFrame();
	return result;
}
N_NIMCALL(int, xputpixel_92692)(tximage80517* ximage, int x, int y, unsigned long pixel) {
	int result;
	nimfr("XPutPixel", "xutil.nim")
	result = 0;
	nimln(384, "xutil.nim");
	result = (*ximage).F.Putpixel(ximage, x, y, pixel);
	popFrame();
	return result;
}
N_NIMCALL(tximage80517*, xsubimage_92699)(tximage80517* ximage, int x, int y, int width, int height) {
	tximage80517* result;
	nimfr("XSubImage", "xutil.nim")
	result = 0;
	nimln(387, "xutil.nim");
	result = (*ximage).F.Subimage(ximage, x, y, width, height);
	popFrame();
	return result;
}
N_NIMCALL(int, xaddpixel_92707)(tximage80517* ximage, long value) {
	int result;
	nimfr("XAddPixel", "xutil.nim")
	result = 0;
	nimln(390, "xutil.nim");
	result = (*ximage).F.Addpixel(ximage, value);
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, iskeypadkey_92712)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsKeypadKey", "xutil.nim")
	result = 0;
	nimln(393, "xutil.nim");
	nimln(393, "xutil.nim");
	LOC1 = 0;
	nimln(702, "system.nim");
	LOC1 = ((NU64)(((unsigned long) 65408)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(393, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65469)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, isprivatekeypadkey_92716)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsPrivateKeypadKey", "xutil.nim")
	result = 0;
	nimln(396, "xutil.nim");
	nimln(396, "xutil.nim");
	LOC1 = 0;
	nimln(702, "system.nim");
	LOC1 = ((NU64)(((unsigned long) 285212672)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(396, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 285278207)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, iscursorkey_92720)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsCursorKey", "xutil.nim")
	result = 0;
	nimln(399, "xutil.nim");
	nimln(399, "xutil.nim");
	LOC1 = 0;
	nimln(702, "system.nim");
	LOC1 = ((NU64)(((unsigned long) 65360)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(399, "xutil.nim");
	LOC1 = ((NU64)(keysym) < (NU64)(((unsigned long) 65376)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, ispfkey_92724)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsPFKey", "xutil.nim")
	result = 0;
	nimln(402, "xutil.nim");
	nimln(402, "xutil.nim");
	LOC1 = 0;
	nimln(702, "system.nim");
	LOC1 = ((NU64)(((unsigned long) 65425)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(402, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65428)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, isfunctionkey_92728)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsFunctionKey", "xutil.nim")
	result = 0;
	nimln(405, "xutil.nim");
	nimln(405, "xutil.nim");
	LOC1 = 0;
	nimln(702, "system.nim");
	LOC1 = ((NU64)(((unsigned long) 65470)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(405, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65504)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, ismiscfunctionkey_92732)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsMiscFunctionKey", "xutil.nim")
	result = 0;
	nimln(408, "xutil.nim");
	nimln(408, "xutil.nim");
	LOC1 = 0;
	nimln(702, "system.nim");
	LOC1 = ((NU64)(((unsigned long) 65376)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(408, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65387)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(NIM_BOOL, ismodifierkey_92736)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC3;
	nimfr("IsModifierKey", "xutil.nim")
	result = 0;
	nimln(411, "xutil.nim");
	nimln(412, "xutil.nim");
	LOC1 = 0;
	nimln(411, "xutil.nim");
	LOC2 = 0;
	nimln(411, "xutil.nim");
	LOC3 = 0;
	nimln(702, "system.nim");
	LOC3 = ((NU64)(((unsigned long) 65505)) <= (NU64)(keysym));
	if (!(LOC3)) goto LA4;
	nimln(411, "xutil.nim");
	LOC3 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65518)));
	LA4: ;
	LOC2 = LOC3;
	if (LOC2) goto LA5;
	nimln(412, "xutil.nim");
	LOC2 = HEX3DHEX3D_79066(keysym, ((unsigned long) 65406));
	LA5: ;
	LOC1 = LOC2;
	if (LOC1) goto LA6;
	nimln(412, "xutil.nim");
	LOC1 = HEX3DHEX3D_79066(keysym, ((unsigned long) 65407));
	LA6: ;
	result = LOC1;
	popFrame();
	return result;
}N_NOINLINE(void, x11xutilInit)(void) {
	nimfr("xutil", "xutil.nim")
	popFrame();
}

N_NOINLINE(void, x11xutilDatInit)(void) {
if (!((TMP140 = nimLoadLibrary((NimStringDesc*) &TMP141))
)) nimLoadLibraryError((NimStringDesc*) &TMP142);
	Dl_92211 = (TY92212) nimGetProcAddr(TMP140, "XAllocClassHint");
	Dl_92214 = (TY92215) nimGetProcAddr(TMP140, "XAllocIconSize");
	Dl_92217 = (TY92218) nimGetProcAddr(TMP140, "XAllocSizeHints");
	Dl_92220 = (TY92221) nimGetProcAddr(TMP140, "XAllocStandardColormap");
	Dl_92223 = (TY92224) nimGetProcAddr(TMP140, "XAllocWMHints");
	Dl_92226 = (TY92227) nimGetProcAddr(TMP140, "XClipBox");
	Dl_92231 = (TY92232) nimGetProcAddr(TMP140, "XCreateRegion");
	Dl_92234 = (TY92235) nimGetProcAddr(TMP140, "XDefaultString");
	Dl_92237 = (TY92238) nimGetProcAddr(TMP140, "XDeleteContext");
	Dl_92243 = (TY92244) nimGetProcAddr(TMP140, "XDestroyRegion");
	Dl_92247 = (TY92248) nimGetProcAddr(TMP140, "XEmptyRegion");
	Dl_92251 = (TY92252) nimGetProcAddr(TMP140, "XEqualRegion");
	Dl_92256 = (TY92257) nimGetProcAddr(TMP140, "XFindContext");
	Dl_92263 = (TY92264) nimGetProcAddr(TMP140, "XGetClassHint");
	Dl_92269 = (TY92270) nimGetProcAddr(TMP140, "XGetIconSizes");
	Dl_92276 = (TY92277) nimGetProcAddr(TMP140, "XGetNormalHints");
	Dl_92282 = (TY92283) nimGetProcAddr(TMP140, "XGetRGBColormaps");
	Dl_92290 = (TY92291) nimGetProcAddr(TMP140, "XGetSizeHints");
	Dl_92297 = (TY92298) nimGetProcAddr(TMP140, "XGetStandardColormap");
	Dl_92304 = (TY92305) nimGetProcAddr(TMP140, "XGetTextProperty");
	Dl_92311 = (TY92312) nimGetProcAddr(TMP140, "XGetVisualInfo");
	Dl_92318 = (TY92319) nimGetProcAddr(TMP140, "XGetWMClientMachine");
	Dl_92324 = (TY92325) nimGetProcAddr(TMP140, "XGetWMHints");
	Dl_92329 = (TY92330) nimGetProcAddr(TMP140, "XGetWMIconName");
	Dl_92335 = (TY92336) nimGetProcAddr(TMP140, "XGetWMName");
	Dl_92341 = (TY92342) nimGetProcAddr(TMP140, "XGetWMNormalHints");
	Dl_92349 = (TY92350) nimGetProcAddr(TMP140, "XGetWMSizeHints");
	Dl_92358 = (TY92359) nimGetProcAddr(TMP140, "XGetZoomHints");
	Dl_92364 = (TY92365) nimGetProcAddr(TMP140, "XIntersectRegion");
	Dl_92370 = (TY92371) nimGetProcAddr(TMP140, "XConvertCase");
	Dl_92376 = (TY92377) nimGetProcAddr(TMP140, "XLookupString");
	Dl_92384 = (TY92385) nimGetProcAddr(TMP140, "XMatchVisualInfo");
	Dl_92392 = (TY92393) nimGetProcAddr(TMP140, "XOffsetRegion");
	Dl_92398 = (TY92399) nimGetProcAddr(TMP140, "XPointInRegion");
	Dl_92404 = (TY92405) nimGetProcAddr(TMP140, "XPolygonRegion");
	Dl_92410 = (TY92411) nimGetProcAddr(TMP140, "XRectInRegion");
	Dl_92418 = (TY92419) nimGetProcAddr(TMP140, "XSaveContext");
	Dl_92425 = (TY92426) nimGetProcAddr(TMP140, "XSetClassHint");
	Dl_92431 = (TY92432) nimGetProcAddr(TMP140, "XSetIconSizes");
	Dl_92438 = (TY92439) nimGetProcAddr(TMP140, "XSetNormalHints");
	Dl_92444 = (TY92445) nimGetProcAddr(TMP140, "XSetRGBColormaps");
	Dl_92452 = (TY92453) nimGetProcAddr(TMP140, "XSetSizeHints");
	Dl_92459 = (TY92460) nimGetProcAddr(TMP140, "XSetStandardProperties");
	Dl_92470 = (TY92471) nimGetProcAddr(TMP140, "XSetTextProperty");
	Dl_92477 = (TY92478) nimGetProcAddr(TMP140, "XSetWMClientMachine");
	Dl_92483 = (TY92484) nimGetProcAddr(TMP140, "XSetWMHints");
	Dl_92489 = (TY92490) nimGetProcAddr(TMP140, "XSetWMIconName");
	Dl_92495 = (TY92496) nimGetProcAddr(TMP140, "XSetWMName");
	Dl_92501 = (TY92502) nimGetProcAddr(TMP140, "XSetWMNormalHints");
	Dl_92507 = (TY92508) nimGetProcAddr(TMP140, "XSetWMProperties");
	Dl_92519 = (TY92520) nimGetProcAddr(TMP140, "XmbSetWMProperties");
	Dl_92531 = (TY92532) nimGetProcAddr(TMP140, "Xutf8SetWMProperties");
	Dl_92543 = (TY92544) nimGetProcAddr(TMP140, "XSetWMSizeHints");
	Dl_92550 = (TY92551) nimGetProcAddr(TMP140, "XSetRegion");
	Dl_92556 = (TY92557) nimGetProcAddr(TMP140, "XSetStandardColormap");
	Dl_92563 = (TY92564) nimGetProcAddr(TMP140, "XSetZoomHints");
	Dl_92569 = (TY92570) nimGetProcAddr(TMP140, "XShrinkRegion");
	Dl_92575 = (TY92576) nimGetProcAddr(TMP140, "XStringListToTextProperty");
	Dl_92581 = (TY92582) nimGetProcAddr(TMP140, "XSubtractRegion");
	Dl_92587 = (TY92588) nimGetProcAddr(TMP140, "XmbTextListToTextProperty");
	Dl_92595 = (TY92596) nimGetProcAddr(TMP140, "XwcTextListToTextProperty");
	Dl_92605 = (TY92606) nimGetProcAddr(TMP140, "Xutf8TextListToTextProperty");
	Dl_92613 = (TY92614) nimGetProcAddr(TMP140, "XwcFreeStringList");
	Dl_92619 = (TY92620) nimGetProcAddr(TMP140, "XTextPropertyToStringList");
	Dl_92625 = (TY92626) nimGetProcAddr(TMP140, "XmbTextPropertyToTextList");
	Dl_92632 = (TY92633) nimGetProcAddr(TMP140, "XwcTextPropertyToTextList");
	Dl_92642 = (TY92643) nimGetProcAddr(TMP140, "Xutf8TextPropertyToTextList");
	Dl_92649 = (TY92650) nimGetProcAddr(TMP140, "XUnionRectWithRegion");
	Dl_92655 = (TY92656) nimGetProcAddr(TMP140, "XUnionRegion");
	Dl_92661 = (TY92662) nimGetProcAddr(TMP140, "XWMGeometry");
	Dl_92675 = (TY92676) nimGetProcAddr(TMP140, "XXorRegion");
}

